### ISSUE TITLE
Bug: Sanitize URL for the repo form

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1007]
### Describe the bug

https://github.com/open-sauced/open-sauced/blob/d7f554e68064e4079e39b7e01ce1d5a6ce130517/src/lib/util.js#L40-L40

This code allows `github.com` URLs but it could be anywhere. To make this secure, we should probably switch to regex. 

[CodeQL](https://securitylab.github.com/tools/codeql/) also alerted us of this.
### To Reproduce

1. Head to opensauced.pizza and log in.
2. Add a URL that includes github.com but not a repo

### Screenshots

Adding a screenshot from CodeQL

![Screen Shot 2021-05-19 at 5 24 22 AM](https://user-images.githubusercontent.com/5713670/118812055-93265200-b862-11eb-8ce8-0cf52602b984.png)

**Comment by filiptronicek** [comment]
Good catch, @bdougie, I think the easier and more JS-native way to do this would be to create a URL object and access its `hostname` property, just like this:
```js
const urlObj = new URL("https://github.com/facebook/react-native/");
console.log(urlObj.hostname); // returns "github.com"
```
and for a URL containing github.com
```js
const urlObj = new URL("https://opensauced.pizza/github.com/wooohooo");
console.log(urlObj.hostname); // returns "opensauced.pizza"
```

I can look further into this.

**Comment by bdougie** [comment]
>  think the easier and more JS-native way to do this would be to create a URL object and access its hostname property

That looks like a good approach. This function also has tests, so it will be pretty straightforward to implement and confirm.

**Comment by mtfoley** [comment]
I'll bite. 
.take

**Comment by mtfoley** [comment]
@filiptronicek please have a look, sir.
