### ISSUE TITLE
Bug: More than 10 Goals makes malformed URLs

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/open-sauced#1014]
### Describe the bug
If someone has more than 10 items in their goals list, any goals beyond the 10th one in the list will have "undefined" in the part of the URL where the issue number should be.  I haven't tracked down exactly how this happens, but I think that the initial state from the goals list uses [SWR](https://swr.vercel.app/) and comes up with greater than 10 line items, while some of the GraphQL queries used for this same list limit to the [first 10](https://github.com/open-sauced/open-sauced/blob/main/src/lib/apiGraphQL.js#L126).
```graphql
query FetchGoals() {
    gitHub {
      viewer {
        repository(name: "open-sauced-goals") {
          id
          data: object(expression: "HEAD:data.json") {
            id
            ... on GitHubBlob {
              id
              text
            }
          }
          issues(
            first: 10
            states: OPEN
            orderBy: { direction: DESC, field: CREATED_AT }
          ) {
            totalCount
            nodes {
              id
              full_name: title
              body
              number
              labels(first: 3) {
                nodes {
                  color
                  name
                  id
                }
              }
            }
          }
        }
      }
    }
  }
```

### To Reproduce
1) Make sure you have more than 10 line items in your goals list
2) Scroll down to 11th or later in the list. 
3) Validate URL ends in undefined.

### Expected behavior
Issue number is used in URL rather than "undefined"

### Screenshots
![Screen Shot 2021-05-19 at 10 52 43 PM](https://user-images.githubusercontent.com/3792749/118911967-0b3d5800-b8f5-11eb-9b3d-90e7e3d7a052.png)

### Desktop

- OS: macOS High Sierra
- Browser: Chrome

### Additional context

When I run locally, I also get a related error about the list in [ListGoals.js](https://github.com/open-sauced/open-sauced/blob/main/src/components/ListGoals.js#L66) needing to have a unique key, and this is due to the fact I have 12+ goal repos, so there's more than one without the goal.id variable set.

**Comment by mtfoley** [comment]
I just noticed that same GQL is tapping the 'data.json' file also, and I'm assuming this is in order to cover the stars and other metadata about the repo since the open-sauced-goals issues list doesn't have a way to track that data. So I think the app populates the goals list with that data.json and then updates with the issue number/ID/etc off of open-sauced-goals. I've got a branch parked in my fork that changes it to first 50, and looks good in my tests for fixing (punting) this.

**Comment by 0-vortex** [comment]
Think @bdougie has some additional context for this, pinging him just to be sure

**Comment by bdougie** [comment]
Confirmed that this is happening for me as well. Thanks for reporting I can take a closer look later today.

**Comment by mtfoley** [comment]
.take

**Comment by mtfoley** [comment]
@bdougie in case you'd like to go this way, I put up PR #1015 .
