### ISSUE TITLE
Bug: Seems like the contributions list and notes reflect bdougie's account

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/open-sauced#1021]
### Describe the bug
When I pull up the site in production and go to one of my goal repos, contributions (issues) by bdougie show up instead of ones I've made. Similar thing for notes.

### To Reproduce
Someone besides bdougie pull up a goal for a repo you've both done contributions (and/or) notes for. I used FiniteSingularity/tau.

### Expected behavior
My issues / PRs would show up under Contributions.

### Screenshots
![Screen Shot 2021-05-29 at 10 32 36 PM](https://user-images.githubusercontent.com/3792749/120090085-ce7c1880-c0cd-11eb-8ecb-3a419942326d.png)

### Desktop

- OS: Mac
- Browser: Chrome
- Version: latest

### Smartphone

- Device:
- OS:
- Browser:
- Version:

**Comment by bdougie** [comment]
Oooops. Looks like it embeds my token. I should fix that.

**Comment by 0-vortex** [comment]
After a lot of reading on both viewer and repository collections and their limitations I figured the simplest way around it would be to use the `involves` feature of the dynamic search endpoints and tested this in the onegraph playground as @bdougie instructed. 

So far what I can tell is that this:
- doesn't need any scope changes
- can be run for any user with the existing app token and/or oauth token 
- fragments can help cache data

Not sure what implementation details this poses but you can play around with it and see for yourself 🍕 

The gist is meant for onegraph but it works on the [github explorer](https://docs.github.com/en/graphql/overview/explorer) if you search and remove the `GitHub` prefixes

https://gist.github.com/0-vortex/c5562ab4e86c3eef1667d91d01abfdac

**Comment by bdougie** [comment]
> Not sure what implementation details this poses but you can play around with it and see for yourself 🍕

This looks great, also a great use of fragments as well. I need to update to include some details that the src/components/IssueListItem.js is looking for, but it mostly works.

**Comment by mtfoley** [comment]
Having trouble reproducing this now but I had also thought a

**Comment by 0-vortex** [comment]
Not sure this is needed but if you have a Mac nearby you can even inspect: 
- https://www.browserstack.com/guide/how-to-debug-on-iphone
- https://appletoolbox.com/use-web-inspector-debug-mobile-safari/

**Comment by mtfoley** [comment]
Same behavior on my trusty dusty 2012 macbook pro at home 🐌 
Contribution section looks fixed to me.  For a future iteration, there are probably options to render issues/PRs in different ways as right now they just have issue icons and comment icons. Here's a screenshot of when `console.table` the result set populating the contributions list.

![Screen Shot 2021-06-16 at 9 58 54 PM](https://user-images.githubusercontent.com/3792749/122319219-4fb91500-ceee-11eb-92e2-1b15874afb4f.png)

Like I said, notes still looks messed up. From a data standpoint, I doubt if the notes feature has really behaved any differently since PR #699 because that's when the goal fetch persisted query was introduced, and i think think the `doc_id2` variable in the persisted graphQL hasn't changed since then.
