### ISSUE TITLE
Bug: User is not logged in breaks CSS

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1042]
### Describe the bug

Not being logged in with GitHub some of the fonts on the mai page are breaking and defaulting to "Times"

### To Reproduce

1. Open a private window
2. Visit https://opensauced.pizza

### Expected behavior

Everything should be perfect, especially FONTS 🗡️ 

### Screenshots

<img width="1341" alt="Screenshot 2021-06-16 at 13 59 27" src="https://user-images.githubusercontent.com/237133/122215374-6e49ec80-ceab-11eb-8116-cf28e60c29f0.png">

<img width="1341" alt="Screenshot 2021-06-16 at 14 02 55" src="https://user-images.githubusercontent.com/237133/122215490-933e5f80-ceab-11eb-998a-bd8413b591ed.png">

### Desktop

- Device: MacBookPro15,4
- OS: 11.5 Beta (20G5033c)
- Browser: Safari 
- Version: 14.1.2 (16611.3.6.1.2)

### Smartphone

- Device: iPhone SE2
- OS: 14.6
- Browser: Safari 
- Version: N/A

**Comment by filiptronicek** [comment]
Looks like this is because of the `Arvo` font, for some reason, it looks like it doesn't load properly. Here is the font on Google Fonts: https://fonts.google.com/specimen/Arvo?query=arvo

**Comment by 0-vortex** [comment]
sounds like an easy fix, should I add this as a goot first issue ?

**Comment by Liberontissauri** [comment]
.take
