### ISSUE TITLE
Bug: Fix dashboard column spacing

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1044]
### Describe the bug

Dashboard is next to repository recommendations.

### To Reproduce

1. Log in 

### Expected behavior

The spacing between the dashboard card and the repository recommendations should be similar to the spacing between dashboard and the add repository box.

### Screenshots

<img width="1303" alt="Screenshot 2021-06-16 at 23 22 42" src="https://user-images.githubusercontent.com/237133/122295685-cd365280-cef9-11eb-94c0-30fb4f103c33.png">

### Desktop

- OS: All
- Browser: All

**Comment by bdougie** [comment]
.take
