### ISSUE TITLE
Bug: Fix dark mode dashboard hover

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1045]
### Describe the bug

Hovering over a repository in the dashboard gives a user a surprise sunburn.

### To Reproduce

1. Log in
2. Hover over a repository you previously added

### Expected behavior

You should be able to read the box content.

### Screenshots

<img width="1341" alt="Screenshot 2021-06-16 at 23 29 57" src="https://user-images.githubusercontent.com/237133/122298252-cd841d00-cefc-11eb-8b6d-01016654fae5.png">

### Desktop

- OS: All
- Browser: All

### Smartphone

- Device: All
- Browser: All

**Comment by bdougie** [comment]
This is a quick fix, hopefully. https://github.com/open-sauced/open-sauced/blob/3af648e3f18d1b2b08ac76a35e482a41c4f19816/src/styles/List.js#L20-L23

Needs the style the Dark Theme applies: https://github.com/open-sauced/open-sauced/blob/main/docs/dark-mode.md

**Comment by mtfoley** [comment]
Fix might actually be latent in [that same file](https://github.com/open-sauced/open-sauced/blob/3af648e3f18d1b2b08ac76a35e482a41c4f19816/src/styles/List.js#L83-87)

**Comment by mtfoley** [comment]
.take

**Comment by mtfoley** [comment]
Fixed in #1060
