### ISSUE TITLE
Bug: Fix dashboard search bar overlap mobile

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1046]
### Describe the bug

The search bar overlaps with the sort panel function.

### To Reproduce

1. Log in
2. Scroll down to the add repository box

### Expected behavior

The 2 sections should switch to block level elements and not overlap each other.

### Screenshots

![image](https://user-images.githubusercontent.com/237133/122299829-c958ff00-cefe-11eb-9807-7ff6d342b309.png)

### Smartphone

- Device: Iphone SE2
- OS: 14
- Browser: Safari

**Comment by miralsuthar** [comment]
I would like to contribute by resolving this issue.

**Comment by mtfoley** [comment]
@miralsuthar that sounds great! Please take a look at [contributing](https://github.com/open-sauced/open-sauced/blob/main/CONTRIBUTING.md) if you haven’t already, and this also talks about how to assign yourself to the issue. Let us know if you have any questions!

**Comment by miralsuthar** [comment]
I solved the issue of leveling the sort option.

can you please check out if it is solved your problem?

![image](https://user-images.githubusercontent.com/57826091/123306188-99cd7680-d53e-11eb-8560-fb708e7e049c.png)

**Comment by miralsuthar** [comment]
I think I have resolved issue #1046

Please review it

![image](https://user-images.githubusercontent.com/57826091/123308143-ee71f100-d540-11eb-8281-192da0338bef.png)

**Comment by mtfoley** [comment]
@miralsuthar thanks for working on this - I can see that you've got a commit to the main branch on your fork. If there's a way for you to put the changes on a new branch named like it's described in the contributing guide I linked to, you can  then create a pull request and we can go from there. Let us know if you have questions on this.

**Comment by miralsuthar** [comment]
I have created the pull request. Can you check it out?
