### ISSUE TITLE
Bug: Dark Mode Theme Button Shows Wrong in Safari

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/open-sauced#1048]
### Describe the bug
The theme button that overrides user's system preference to active dark mode (it's a moon icon) doesn't have the rotation right in Safari. From what I've read briefly, there is probably a fix by editing the SVG markup: https://stackoverflow.com/questions/48248512/svg-transform-rotate180-does-not-work-in-safari-11

### To Reproduce
1) Open opensauced.pizza in Safari for MacOS or iOS.

### Expected behavior
Moon icon is shown with moon at 45 deg angle facing upper right.

### Screenshots
bottom of screenshot is safari, top is chrome.
![Screen Shot 2021-06-16 at 10 17 37 PM](https://user-images.githubusercontent.com/3792749/122321023-32397a80-cef1-11eb-8991-7a8b9446fb38.png)

### Desktop

- OS: mac
- Browser: Safari
- Version: v14.1.1

### Smartphone

- Device: iphone 8
- OS: iOS
- Browser: safari
- Version: latest, dunno

**Comment by Daniel-Singer** [comment]
Hi @mtfoley ! I would like to help if thats ok. Can´t promise anything, but sounds like a good challenge

**Comment by mtfoley** [comment]
Sounds great @Daniel-Singer - you should find some instructions about how to contribute in fixing issues in [contributing](./CONTRIBUTING.md)

**Comment by jason1985** [comment]
Hi @mtfoley.  I was just curious as to if it's possible to reproduce this bug without having access to Safari, iOS, or MacOS?  Is there a standard free emulator or something like that?
Thanks!

**Comment by jason1985** [comment]
.take

**Comment by Daniel-Singer** [comment]
Hi! I tried to fix it but unfortunately my Safari installation is not able to open the site. All i know is that safari does not support transform: rotate on svg elements.

**Comment by 0-vortex** [comment]
I can help with this

**Comment by mtfoley** [comment]
@Daniel-Singer would you have any interest in looking at #1045? It would deal with CSS in styled-components and I think we've gotten as far as figuring out which file would need to be changed.

**Comment by bdougie** [comment]
@jason1985 has opened a PR for this. @Daniel-Singer feel free to poke about the [good first issues](https://github.com/open-sauced/open-sauced/contribute) for another

**Comment by Daniel-Singer** [comment]
I will , thank you,
