### ISSUE TITLE
Feature: storybook-dark-mode

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1053]
### Is your feature request related to a problem? Please describe.

https://storybook.js.org/addons/storybook-dark-mode

### Describe the solution you'd like

Include darkmode in the design.opensauced.pizza

### Describe alternatives you've considered

Thue plugin is the best path forward.

### Additional context

this will need to wait for #1037

**Comment by mtfoley** [comment]
.take

**Comment by mtfoley** [comment]
Closed in #1061
