### ISSUE TITLE
Bug: figure out a way to clean up missing projects from the dashboard

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1065]
### Describe the bug

Assuming you added a repository to the dashboard that changes remote or becomes private, clicking on it will throw a red error message in between the header and the boxed content saying it cannot find the specified repository, however the user is not presented with a way to remove the faulty project.

We need to figure out a way to remove that repository from the dashboard, potential candidates:
- removing it from the list automatically
- unblocking the "remove project" button in the repository view
- getting presented with a modal message requiring some form of more advanced resolution (keep your notes)

### To Reproduce

1. Add something like `torvalds/linux`
2. Get `Repository "torvalds/linux" not found` error

### Expected behavior

It should fail, but with a potential for resolution.

### Screenshots

<img width="1407" alt="Screenshot 2021-06-30 at 12 23 42" src="https://user-images.githubusercontent.com/237133/123945676-b0d8f200-d99e-11eb-936e-c5ad660882c9.png">

### Desktop

- All

### Smartphone

- All

**Comment by filiptronicek** [comment]
I think we maybe could just close the issue if the error returns a 404 and add a popup/error toast on the homepage.

**Comment by 0-vortex** [comment]
Adding a toast on the homepage I feel is worse, you then want to clean it up and can't :D

**Comment by filiptronicek** [comment]
I guess so, so maybe a popup? Like a Sweet Alert one? Just saying "this repo could no longer be indexed/fetched", are you sure you have given Open Sauced the right permissions or the repo wasn't removed?" or something like that.

**Comment by 0-vortex** [comment]
What about the times when the user has done nothing wrong to get to this flow ? I'm sorry but not seeing any argument for this not being a bug or a needed feature. Maybe a silly allegory, but if one decides some thing they own is trash, sooner or later they will throw it away - in open sauced, currently, we can only throw away things that are not trash :D

Was hoping we can focus discussion around how to graciously remove it, your suggestion for the popup + notification is awesome for when we are mutating the list IE remove the repo from the dashboard for the user -> alert him, that's still not solving the issue, just a good end user resolution. 

Honestly have not investigated the technicality of doing this but assumed it's not that hard

**Comment by filiptronicek** [comment]
Your comment makes sense, I probably didn't think it through completely. We could first use a background check (I think we already have some sort of GitHub Action in the goals repo), that could also check for missing repos, and removing them and for the frontend add an error message if a user clicks on / goes to a repo, which is inaccessible.

**Comment by 0-vortex** [comment]
Thought we had an action to fix that, if we do and it's failing only for a specific use case we should investigate what happened - missing what happens when a public repo goes private or gets banned; for what it's worth the mentioned repository exists at [torvalds/linux](https://github.com/torvalds/linux), only thing I can definitely see is over 1 million commits :D

If you have any ideas how to edit the OP issue wording to make it more clear please go ahead and do it; it's not common to add notes to such a big repository for the purpose of contributing but definitely a valid and popular use case for taking notes and keeping up to date with - expect most people missing out on open source to have that as one of their initial markers looking to learn

**Comment by filiptronicek** [comment]
This leads me to wonder, what exactly it is about Linux that makes the query fail. The number of commits is notable, but AFAIK there is no point in which we fetch any of the commits (or do we?), but maybe it has something to do with the contributors because there's more than 5,000 contributors, and the REST API returns this:
```json
{
  "message": "The history or contributor list is too large to list contributors for this repository via the API.",
  "documentation_url": "https://docs.github.com/rest/reference/repos#list-repository-contributors"
}

```

**Comment by 0-vortex** [comment]
ah, that makes a lot of sense ! maybe for this use case it is important to not let the user add it, before we find a resolution

**Comment by filiptronicek** [comment]
I'd say maybe we don't have to limit ourselves that much, maybe just don't show any contributors when they aren't available? I think the rest of the fields should be available and for folks who want to add notes to such projects, I say we let 'em 😄 .

![image](https://user-images.githubusercontent.com/29888641/124380928-e859de00-dcbf-11eb-8991-e0c4b8cb1229.png)

**Comment by 0-vortex** [comment]
> I'd say maybe we don't have to limit ourselves that much, maybe just don't show any contributors when they aren't available? I think the rest of the fields should be available and for folks who want to add notes to such projects, I say we let 'em 😄 .
> 
> ![image](https://user-images.githubusercontent.com/29888641/124380928-e859de00-dcbf-11eb-8991-e0c4b8cb1229.png)

You mean making just that container return error while letting the user still remove the repo if he doesn't want it ? That would totally make the linux repo usable too !

**Comment by filiptronicek** [comment]
Yep, I think we can either hide it, or put some text in it (like "too many contributors", "5000+ contributors", "error loading contributors"). That would solve the issue hopefully. What do you think?

**Comment by 0-vortex** [comment]
100% on board with this - the actual fix would split the initial request into repo and contributions into a second request thus making the rest of the page available. Can't `.take` this since I am working on 2 other pulls right now :D
Should we update the issue description or just close it in favour of a better worded one?

**Comment by 0-vortex** [comment]
Guess we can improve the take workflow to check if the issue comment starts with it rather than anywhere in the text ? 🍕

**Comment by filiptronicek** [comment]
Yes, for sure we could improve the take workflow, this should not happen 😄

**Comment by filiptronicek** [comment]
> 
> 
> 100% on board with this - the actual fix would split the initial request into repo and contributions into a second request thus making the rest of the page available. Can't `.take` this since I am working on 2 other pulls right now :D
> Should we update the issue description or just close it in favour of a better worded one?

I think this issue should be split into two: one about repos which no longer can be accessed by us, and the other one about repos with too many contributors.

**Comment by 0-vortex** [comment]
Agreed, you have the honour of opening the other issue :D

**Comment by mtfoley** [comment]
Haven't had much opportunity to look at code for this but is it using a persisted query right now?

**Comment by filiptronicek** [comment]
@0-vortex I think the problem with Linux has been reported by you back in April in https://github.com/open-sauced/open-sauced/issues/949
