### ISSUE TITLE
Bug: Pin down actions/setup-node to specific versions

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1080]
### Is your feature request related to a problem? Please describe.

Terribly frustrated by the amount of issues around tooling and the confusion created by not being able to successfully pass workflows exemplifying best practices.

The setup action we are using has historic SemVer inconsistencies like `v2.0.0` to `v2.1.5` being tagged as `v2-beta` while `v2.2.0` is the first official v2. Sticking to `v2` in its current state will cause following side effects:
- `npm` is not fully tested, we ran into issues before `v2.2.0` so it could happen again
- `octoherd` will request to update our workflows with new features like cache
- cache function only works with single committer flow

### Describe the solution you'd like

- switch `v2` to the proper version that works for all our use cases IE `v2.1.5`
- document this change and how to check when a file/line was committed
- document all our historic issues so new contributors don't waste time trying to upgrade this action

### Describe alternatives you've considered

- writing our own node setup action
- patching `actions/node-setup` in our own fork
- quitting open source

### Additional context

Will not be bullied into replacing `npm` with `yarn`, especially when there are so many package managers out there and open-sauced works just fine with all of them.
Not having predictable results we lose engagement, contributor happiness, create confusion and diverge from both specification and best practices.
Having maintainers keep a closer eye to our dependencies and locking them down will avoid scrutiny in other areas as well and keep us from getting surprise-blocked.

**Comment by filiptronicek** [comment]
@0-vortex I agree with most of your points, this version confusion is for sure something to focus on. At this point I'm probably a bit out of sync, but is it now so that we are using v2.1.5 or v2.2.0? If we are using 2.2.0, we could maybe pin the version to 2.2.x? 

A page in our docs dedicated to this issue would be an awesome addition for sure (along with mentioning your point about most package managers working with Open Sauced). 

As an alternative, option 3 looks like a very good solution to this problem, but it's [a permanent solution to a temporary problem](http://www.suicide.org/permanent-solution-to-a-temporary-problem.html) 😄 (my apologies).

**Comment by 0-vortex** [comment]
Sorry if the ticket sounded dark, was just trying to be serious 😅

Staying on v2 we would get all the upcoming features which should be discussed among maintainers rather than fast-forwarded. 

Less living on the edge :D

**Comment by filiptronicek** [comment]
Totally agreed, staying on full releases is probably the way to go here. It will give us time to prepare for breaking changes.

**Comment by bdougie** [comment]
> document this change and how to check when a file/line was committed

The fact that there are discrepancies with what v2 is, is concerning. However, I am hoping the 

> cache function only works with single committer flow

Is this related to the open #1079?

**Comment by 0-vortex** [comment]
> Is this related to the open #1079?

Yes, we should not stay on major versions for actions that don't have predictable results for open sauced, have a strong dislike for closing pull requests 😞
