### ISSUE TITLE
Feature: Make GitHub Actions permissions reusable across all workflows. 

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1081]
### Is your feature request related to a problem? Please describe.

The potential usages of [actions/github-script](https://github.com/actions/github-script) and other authentication required workflows could be made easier to debug and collaborate on by enabling the [permissions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions) syntax and documenting it in our contributing docs.

_Optionally adhere to long term support GitHub API endpoints_

### Describe the solution you'd like

- apply minimal `permissions` to current workflows
- require every new workflow specify the minimum permissions 
- investigate fully permissive [github_token](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/disabling-or-limiting-github-actions-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository) 
- document all the available `$GITHUB_TOKEN` scopes and workflow contexts
- document and optimistically discouraging using to the GitHub API experimental flags in workflows

### Describe alternatives you've considered

Actions documentation is not exactly first-time contributor friendly, could not think of other alternatives to make workflows more accessible.

### Additional context

Should prevent pulls like [jlengstorf/open-sauced#1](https://github.com/jlengstorf/open-sauced/pull/1) from failing in the future by promoting only production endpoints and making the permissions predictable before the pull request is opened.

Optimistically discouraging experimental flags is not saying no, but rather preparing contributors for potential bumpy rides and giving them better tools to debug issues.

**Comment by filiptronicek** [comment]
@0-vortex awesome that you bring this up. I know it's probably obvious, but I think it's important to note that yes, in fact, giving all workflows the same permissions is a bad decision, as some workflows will have insufficient permission to do the thing they are supposed to and some will have too many permissions, which they shouldn't ever need.

**Comment by bdougie** [comment]
I agree with this approach but have not gotten around to implementing this as of yet. In preparation for the permission feature shipping, I created the [pr-audit-target](https://github.com/open-sauced/open-sauced/blob/main/.github/workflows/pr-audit-target.yml).

This could get the following permission to :

```yml
permissions:
  pull-requests: write
  actions: write
  statuses: read
```

**Comment by 0-vortex** [comment]
> I agree with this approach but have not gotten around to implementing this as of yet. In preparation for the permission feature shipping, I created the [pr-audit-target](https://github.com/open-sauced/open-sauced/blob/main/.github/workflows/pr-audit-target.yml).
> 
> This could get the following permission to :
> 
> ```yaml
> permissions:
>   pull-requests: write
>   actions: write
>   statuses: read
> ```

Oh `pull_request_target` is a topic in itself, I was thinking less [advanced minimalism](https://github.blog/2021-04-13-implementing-least-privilege-for-secrets-in-github-actions/) for step 1, in the sense of adjusting our current workflows with progressive improvements - you already took the necessary precautions to avoid data leaking in forks so this would be consolidating then in the config.

For the linked workflow, what do you think about building 2 of the same workflow, one `pull_request` and one `pull_request_target` to document the exact security implications and feature differences?

**Comment by 0-vortex** [comment]
.take

**Comment by mtfoley** [comment]
testing .take update
