### ISSUE TITLE
Feature: Update logo for use-shopping-cart

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/open-sauced#1084]
### Is your feature request related to a problem? Please describe.

During the implementation of dark mode, it came up that the logo for use-shopping-cart on the splash page should be updated. Looks like with their release 3.0, there's a new logo in use.

### Describe the solution you'd like

Update the logo to the one in use at https://useshoppingcart.com

### Describe alternatives you've considered

N/A

### Additional context

Screenshot of existing logo, mobile safari
![image](https://user-images.githubusercontent.com/3792749/125323354-b0304c00-e30c-11eb-9f90-8dac17e604b9.png)

**Comment by filiptronicek** [comment]
@mtfoley awesome that you noticed! I found the SVG version of their logo in their repo, may be useful:
https://raw.githubusercontent.com/dayhaysoos/use-shopping-cart/master/docs/static/img/usc-logo.svg

**Comment by 0-vortex** [comment]
good catch !

**Comment by daptheHuman** [comment]
.take
