### ISSUE TITLE
Bug: add ability to switch between open-sauced and docs

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1089]
### Describe the bug

The [docs](https://docs.opensauced.pizza) is missing a "home" button, both the logo and the "docs" link going back to the docs endpoint

### To Reproduce

1. Go to https://docs.opensauced.pizza
2. Never go back

### Expected behavior

Should be able to visit docs and opensauced.pizza without opening a new tab

### Screenshots

<img width="322" alt="Screenshot 2021-07-15 at 13 49 16" src="https://user-images.githubusercontent.com/237133/125783361-82c5a56a-c553-4801-95eb-bcec436098d8.png">

### Desktop

- OS:
- Browser:
- Version:

### Smartphone

- Device:
- OS:
- Browser:
- Version:

**Comment by 0-vortex** [comment]
@daptheHuman the take step described here: https://docs.opensauced.pizza/contributing/getting-started/#issues should assign you to the issue you opened the PR for 🍕

**Comment by daptheHuman** [comment]
.take
