### ISSUE TITLE
Feature: add categories to docs footer

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1090]
### Describe the bug

The [docs](https://docs.opensauced.pizza) is missing the navigation categories from the sidebar in the footer. We should populate that area with some "top" articles if not categories themselves.

### To Reproduce

1. Go to https://docs.opensauced.pizza
2. Check the "Docs" section in footer

### Expected behavior

Have better links in the footer.

### Screenshots

<img width="260" alt="Screenshot 2021-07-15 at 13 53 42" src="https://user-images.githubusercontent.com/237133/125783833-c06451fa-f542-4f35-826d-4bec95e77c93.png">

### Desktop

- OS:
- Browser:
- Version:

### Smartphone

- Device:
- OS:
- Browser:
- Version:

**Comment by daptheHuman** [comment]
.take
