### ISSUE TITLE
Feature: investigate search plugins for the docs endpoint

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1091]
### Is your feature request related to a problem? Please describe.

Navigating the [docs](https://docs.opensauced.pizza) seems easy but it could use some wildcard searching

### Describe the solution you'd like

Something that makes sense for us from [docusaurus docs](https://docusaurus.io/docs/search)

### Describe alternatives you've considered

No search.

**Comment by filiptronicek** [comment]
I think they have built in support for Algolia, right? It should be as easy as applying and turning it on.

**Comment by 0-vortex** [comment]
> I think they have built in support for Algolia, right? It should be as easy as applying and turning it on.

The ticket is also about researching if Algolia is still the best choice 😛 - but tl;dr: **yes**

**Comment by bdougie** [comment]
I just submitted for https://docsearch.algolia.com/apply/. They should be in touch.

**Comment by filiptronicek** [comment]
@0-vortex oh right, makes sense, I think I never saw anything else than Algolia, but I love the results, they never let me down. I think Algolia would be super. Wouldn't it require additional resources to create the search index if we used something like [docusaurus-lunr-search](https://www.npmjs.com/package/docusaurus-lunr-search)?

**Comment by 0-vortex** [comment]
closing in favour of #1106
