### ISSUE TITLE
Collect Data and create an Open Sauced recommendation feed

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1096]
## user story
As a user, I would like to see what projects others are starring and contributing to.

## approach

```
// data.json
{
 [],
}

// stars.json
{
  [],
}
```

- [x] Collect user's star data and save it to the data.json along with goal data https://github.com/open-sauced/actions/pull/4
- [x] #1138
- [x] #1132
- [x] #1133

## more info
consider using [flatdata](https://github.com/marketplace/actions/flat-data)

The idea that I had was to include repositories that a user has starred in open sauced. My thought comes from the idea that sometimes I will star a repo for a particular reason and after a while I forget why I starred it. It would be great if I could also have that repository show up in open-sauced so that I can include notes about why I starred the repo.

_Originally posted by @jasonericdavis in https://github.com/open-sauced/open-sauced/issues/344#issuecomment-821582717_

**Comment by mtfoley** [comment]
I looked thru flat data repos a little today. Looks like data acquisition right now would be limited to SQL, CSV via HTTP and maybe others.  However, someone did open an issue recently with respect to GraphQL: https://github.com/githubocto/flat/issues/53

**Comment by mtfoley** [comment]
From what I’ve read flatdata now supports graphql via extra parameters to HTTP setup. Example here: https://github.com/githubocto/flat-demo-graphql

**Comment by bdougie** [comment]
https://github.com/open-sauced/goals-template/pull/22#issuecomment-887889341

**Comment by bdougie** [comment]
FYI, the installation_id will need to be removed when this is read

https://github.com/open-sauced/actions/blob/main/open-sauced-admin/action.js#L14

At the moment it is only updating my repo (bdougie/open-sauced-goals).

**Comment by mtfoley** [comment]
FWIW this was a fun query to look at in https://explore.opensauced.pizza

Shows the people you follow and lists the repos they're watching.

```graphql
query MyQuery {
  gitHub {
    viewer {
      bio
      login
      contributionsCollection {
        totalCommitContributions
        totalIssueContributions
        endedAt
        startedAt
        totalRepositoryContributions
      }
      following(first: 10) {
        edges {
          node {
            id
            login
            avatarUrl
            watching(
              first: 10
              orderBy: {field: STARGAZERS, direction: DESC}
              isLocked: false
            ) {
              edges {
                node {
                  id
                  name
                  primaryLanguage {
                    name
                    color
                  }
                  hasIssuesEnabled
                }
              }
            }
          }
        }
      }
    }
  }
}

```

**Comment by mtfoley** [comment]
Since it didn't work on stream 💔 
![image](https://user-images.githubusercontent.com/3792749/128938314-8d0486e7-6fcf-470f-8a36-c32191bf8627.png)

**Comment by bdougie** [comment]
For the algorithm consider the following:
- check API event data for starred date
-

**Comment by bdougie** [comment]
The scope of this has increased. We are not using the above data in the https://hot.opensauced.pizza and https://github.com/open-sauced/hot

**Comment by 0-vortex** [comment]
I have some ideas for this, need to finish the vite and cloud updates before I can present any serverless github actions magic :D

**Comment by 0-vortex** [comment]
[open-sauced/api](https://github.com/open-sauced/api.opensauced.pizza) 🍕
