### ISSUE TITLE
Docs: Fix a few typos in GraphQL Docs

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/open-sauced#1100]
### Describe the improvement

There are a few typos to fix in the GraphQL docs.

**Comment by mtfoley** [comment]
.take

**Comment by mtfoley** [comment]
I stepped slightly off scope, but it was convenient to try tabulating the API calls and how the components use them.

**Comment by mtfoley** [comment]
Seems like https:
//docs.opensauced.pizza still has old version of this docs file, so deployment may still be required here @bdougie

**Comment by 0-vortex** [comment]
> Seems like [docs page](https://docs.opensauced.pizza) still has old version of this docs file, so deployment may still be required here @bdougie

Think that is another issue, made some bad assumptions :D 

```
SyntaxError: /home/runner/work/open-sauced/open-sauced/docs/docs/contributing/fetching-data-from-github.md: Expected corresponding JSX closing tag for <br>. (35:134)
```

**Comment by mtfoley** [comment]
Just clobbered your comment... GitHub app apparently alludes me, lol

**Comment by mtfoley** [comment]
Reopening because of deployment issue described above…
