### ISSUE TITLE
Enable Docsearch on docs.opensauced.pizza

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1106]
# What is this?

I just confirmation from Algolia that we have access to their free docsearch tool. They will crawl the docs site and share the search results.

https://github.com/algolia/docsearch-configs/blob/master/configs/opensauced.json

# Implementation

Docusaurus supports search using Algolia DocSearch. Once your website is online, you can submit it to DocSearch. Algolia will then send you credentials you can add to your siteConfig.js.

- [Instruction to implement](https://v1.docusaurus.io/docs/en/search)
- Create siteConfig.js in the [root of the docs](https://github.com/open-sauced/open-sauced/tree/main/docs) folder

```js
const siteConfig = {
  ...
  algolia: {
    apiKey: '1691a4a5b06166984397aa30153f663c',
    indexName: 'opensauced',
    algoliaOptions: { 'facetFilters': ["type:$TYPE"] },
    debug: false // Set debug to true if you want to inspect the dropdown
  },
  ...
};

```

**Comment by 0-vortex** [comment]
Sounds like something I should tackle 🔥

**Comment by bdougie** [comment]
Yeah, should be straightforward.

**Comment by bdougie** [comment]
.take
