### ISSUE TITLE
Feature: Open Sauced release-ops in this and other repos.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1107]
### Is your feature request related to a problem? Please describe.

Today releases are no longer automated due to tons of issues. I ended it all out of frustration. Releases were inconsistent and now we are only pushing tags. 

Can we copy what is happening in the https://github.com/open-sauced/explore.opensauced.pizza?

### Describe the solution you'd like

Octoherd is a good solution for this, but open to other ideas. 

### Describe alternatives you've considered

Make the release-ops reusable across multiple repos. 

### Additional context

- Link to future Twitch clip
- [Example of a generated release](https://github.com/open-sauced/explore.opensauced.pizza/releases)
- [workflow example](https://github.com/open-sauced/explore.opensauced.pizza/blob/main/.github/workflows/release.yml)

![Screen Shot 2021-07-27 at 1 53 49 PM](https://user-images.githubusercontent.com/5713670/127225922-2fec6a5c-4106-4f6f-8834-2c2dbff034b3.png)

```sh
// example of an octoherd

npx octoherd-script-copy-files \
  --template open-sauced/explore.opensauced.pizza
  --repo open-sauced/open-sauced
```

**Comment by 0-vortex** [comment]
.take
