### ISSUE TITLE
Feature: webpack 5 dependency updates

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1131]
### Is your feature request related to a problem? Please describe.

Some of our dependencies could use some major version / breaking changes updates:
- [css-loader](https://www.npmjs.com/package/css-loader) requires some `file-loader` and `url-loader` updates as described in: [6.0.0](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#600-2021-07-14)
- [mini-css-extract-plugin](https://www.npmjs.com/package/mini-css-extract-plugin) requires some `webpack@5` updates as described in: [2.0.0](https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/CHANGELOG.md#200-2021-06-30)
- [postcss-loader](https://www.npmjs.com/package/postcss-loader) requires some `webpack@5` updates as described in: [5.0.0](https://github.com/webpack-contrib/postcss-loader/blob/master/CHANGELOG.md#500-2021-02-02)
- [webpack-manifest-plugin](https://www.npmjs.com/package/webpack-manifest-plugin) requires some `webpack@5` updates as described in: [3.0.0](https://github.com/shellscape/webpack-manifest-plugin/releases/tag/v3.0.0)
- [webpack](https://www.npmjs.com/package/webpack) requires a lot of updates as described in: [5.0.0](https://webpack.js.org/blog/2020-10-10-webpack-5-release/)
- [webpack-dev-server](https://www.npmjs.com/package/webpack-dev-server) requires a few minor updates as described in: [4.0.0](https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#400-rc0-2021-07-19)

### Describe the solution you'd like

Update webpack to version 5, update all the dependencies, then ping a maintainer to help with the major webpack updates - doing this without the peer dependencies is gruesome if not potentially impossible and should be handled in one go!

### Describe alternatives you've considered

Switch to snowpack, which is a great idea, however, without this update, we cannot accurately tell how good/big of an improvement snowpack is.

**Comment by mtfoley** [comment]
I completely missed the point of this issue and ran off to port Open Sauced to use snowpack 🙄 

Haven't tested it in many places, but I managed to get it running in my last commit to:
https://github.com/mtfoley/open-sauced/tree/snowpack-rework

The only casualty I've had so far is having to punt in hard coding the version number of the app, as this used the `!json:` syntax:
https://github.com/mtfoley/open-sauced/commit/0fffbcc42ebc68c59eefbde5c06c044a6367489d
There's probably a good way to do this, I just haven't researched it yet.

@bdougie @0-vortex let me know if you think I should just start a PR to see how the netlify preview looks. I haven't attempted to see what the best course is on running tests yet, so there may be a hold up there anyhow.

**Comment by 0-vortex** [comment]
> I completely missed the point of this issue and ran off to port Open Sauced to use snowpack 🙄
> 
> Haven't tested it in many places, but I managed to get it running in my last commit to: https://github.com/mtfoley/open-sauced/tree/snowpack-rework
> 
> The only casualty I've had so far is having to punt in hard coding the version number of the app, as this used the `!json:` syntax: [mtfoley@f941072](https://github.com/mtfoley/open-sauced/commit/f941072cf1b2d1dad068b26bfec71c1c4024e6fd) There's probably a good way to do this, I just haven't researched it yet.
> 
> @bdougie @0-vortex let me know if you think I should just start a PR to see how the netlify preview looks. I haven't attempted to see what the best course is on running tests yet, so there may be a hold up there anyhow.

Hey I'm not a big fan of webpack either 🍕 
I'm anxious to see the PR, if it's working on your machine it sounds like a pretty ready to test version, but we could still check for bugs together :D
