### ISSUE TITLE
Discover algorithm to aggregate the data as recommendations (TikTok).

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1133]
I would love to take all stars.json data and make smart recommendations to users. 

I think @mtfoley's exploration maybe be able to kick start this https://github.com/open-sauced/open-sauced/issues/1096#issuecomment-895393140

**Comment by LobRockyl** [comment]
I want to contribute to this. Could you assign it?

**Comment by 0-vortex** [comment]
> I want to contribute to this. Could you assign it?

Not against it but it's not a one man effort for sure :D

**Comment by LobRockyl** [comment]
> > I want to contribute to this. Could you assign it?
> 
> Not against it but it's not a one man effort for sure :D

So how do I/we contribute to this?

**Comment by 0-vortex** [comment]
For actual contributions we have developer documentation available at [docs.opensauced](https://docs.opensauced.pizza) that should help describe what the project is about, at least technically. For the hard part of the ticket, we encourage you to join discord and start a conversation, we're doing our best to help people feel welcome and answer questions!

**Comment by bdougie** [comment]
Jumping in to state is currently blocked by me. We first need the data, which is being populated by https://github.com/open-sauced/actions/pull/13.

I need to figure out how to expose it as a public API.

## What we have so far

- Collecting stars from each user (last 30 only). 
- Comparing data to find out how many open sauced users are starting the same project.
- Identifying how recent the project was starred and applying a recency value to it. 

## What is next?
- What data should we collect to identify if a project is worth recommending? (forks, star count, contributions, etc?)

**Comment by bdougie** [comment]
Jumping in to state is currently blocked by me. We first need the data, which is being populated by https://github.com/open-sauced/actions/pull/13.

I need to figure out how to expose it as a public API.

## What we have so far

- Collecting stars from each user (last 30 only). 
- Comparing data to find out how many open sauced users are starting the same project.
- Identifying how recent the project was starred and applying a recency value to it. 

## What is next?
- What data should we collect to identify if a project is worth recommending? (forks, star count, contributions, etc?)

**Comment by git-srinivas** [comment]
> Jumping in to state is currently blocked by me. We first need the data, which is being populated by [open-sauced/actions#13](https://github.com/open-sauced/actions/pull/13).
> 
> I need to figure out how to expose it as a public API.
> 
> ## What we have so far
> * Collecting stars from each user (last 30 only).
> * Comparing data to find out how many open sauced users are starting the same project.
> * Identifying how recent the project was starred and applying a recency value to it.
> 
> ## What is next?
> * What data should we collect to identify if a project is worth recommending? (forks, star count, contributions, etc?)
> 
> > So how do I/we contribute to this?
> 
> @LobRockyl thoughts on an approach is a welcomed contribution

To expose it as a public repo:
1.supabase provides APIs to access data from tables/ collections.

Recommendations:
1. Why can't we display all 3 categories Ike 
#mostforked 
#moststarred
#mostcontributed

**Comment by bdougie** [comment]
Following up, here again, to say we have now started collecting and sharing data in supabase using the [hot.opensauced.pizza](https://hot.opensauced.pizza). The plan is to grow users and then start sharing the data based on the discovered algorithm.
