### ISSUE TITLE
Bug: contributing guide link is broken

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/open-sauced#1136]
### Describe the bug

In the README file, the link to contributing guide is broken, probably after splitting docs to its own repo.

### To Reproduce
View readme, follow link 

### Expected behavior
Should probably open to [https://docs.opensauced.pizza/contributing/getting-started/](https://docs.opensauced.pizza/contributing/getting-started/)

### Screenshots
N/A

### Desktop

- OS:
- Browser:
- Version:

### Smartphone

- Device: iPhone 8
- OS: iOS latest
- Browser: safari
- Version: ?

**Comment by mtfoley** [comment]
Came across this while commenting on #1109 earlier today

**Comment by MukulKolpe** [comment]
Hey @mtfoley, can I work on this issue?

**Comment by mtfoley** [comment]
Sounds great! First take some time to read over the [contributing guide](https://docs.opensauced.pizza/contributing/getting-started/) including the part about how to assign yourself to the issue.

**Comment by MukulKolpe** [comment]
.take

**Comment by MukulKolpe** [comment]
Hey @mtfoley, Thank you for letting me know this!!
