### ISSUE TITLE
Create a Set checker to limit the recommendation list to only repos that are not on the list.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1138]
Could this be improved using a [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) instead of an n+1? https://github.com/open-sauced/open-sauced/blob/main/src/lib/manageStarData.js#L12.

## What are we looking for?

I would love anyone who contributes to this to show the performance improvement in the PR as well. Please ask questions 🙏🏾

**Comment by vickywane** [comment]
@bdougie can you please provide some more description on what is required here? 

I would like to attempt a fix to it.

**Comment by mtfoley** [comment]
> @bdougie do you mean to improve the filter and find code in `filterForUniqueStars`  method?

Check out this video, maybe around 1-2 mins in. Might help with context...

https://m.youtube.com/watch?v=Oa7VyTNnsc4
