### ISSUE TITLE
Feature: Arrange project to better manage static assets

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/open-sauced#1155]
### Type of feature

Refactor

### Current behavior

In order to accomplish storybook dark mode (#1061) `src/index.css` was copied to `.storybook/`.

However, now that remirror note editing (#1105) has been completed, these files have fallen out of sync.

There may be other cases like this one but I feel the static asset handling required both by the main project and also the design system could be better managed.

### Desired solution

I don't have a specific solution in mind, but I just know that changes coming to the design system might be affected by the way things currently are.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mtfoley** [comment]
also @0-vortex I'm loving these new issue forms 💯

**Comment by 0-vortex** [comment]
feels like a good first issue, exploring CSS in open sauced and storybook, what do you think?

**Comment by 0-vortex** [comment]
.take

**Comment by 0-vortex** [comment]
With vite this one is easy to move around now, no more moving parts :D
