### ISSUE TITLE
Feature: Make the basic template not a button, but instead a link

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1159]
### Type of feature

Fix

### Current behavior

Today it looks like this. 
![Screen Shot 2021-09-22 at 2 12 02 PM](https://user-images.githubusercontent.com/5713670/134423010-ff71898c-5526-41e6-8f07-1d6bc2ada449.png)

### Desired solution

It would be nice to have it as a standard link.

### Additional context

Look in the existing storybook or design system for how to do this. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nayabatir1** [comment]
@bdougie may I help

**Comment by mtfoley** [comment]
@nayabatir1, we’d love to have your help! Take a look at our [contribution docs](https://docs.opensauced.pizza/contributing/getting-started/), including the section that talks about how to assign yourself to the issue.

**Comment by nayabatir1** [comment]
@mtfoley can you do KT about this issue I am unable to figure it out.

**Comment by 0-vortex** [comment]
> @mtfoley can you do KT about this issue I am unable to figure it out.

https://docs.opensauced.pizza/contributing/getting-started/#issues

**Comment by 0-vortex** [comment]
If you happen to run into issues please let us know if the docs are incomplete!

**Comment by nayabatir1** [comment]
> If you happen to run into issues please let us know if the docs are incomplete!

I don't understand #1159. 😕 
I'm not stuck just that I need more details about the above issue.

>Look in the existing storybook or design system for how to do this.

How to navigate to storybook or where can I find design system.

**Comment by mtfoley** [comment]
@nayabatir1 I think that the issue is calling to change this piece of code:
https://github.com/open-sauced/open-sauced/blob/6b2771f51adadbd50305bde24d1f1b5332ee12c1/src/components/NoteFormSocial.js#L51-L53

so it would go to maybe reading, one of these, depending on what looks best:
```js
// import at top of page
import { AccentLink, SubtleLink } from "../styles/Typography";
```
```jsx
// SubtleLink
<SubtleLink  href="#" rel="noreferrer" onClick={startNewNote}>
  Basic Template
</SubtleLink>

// AccentLink
<AccentLink  href="#" rel="noreferrer" onClick={startNewNote}>
  Basic Template
</AccentLink>

// Standard Link
<a href="#" rel="noreferrer" onClick={startNewNote}>
  Basic Template
</a>

```

Disclaimer: There might be more to this in terms of preventing default behavior on clicking the link.  In searching the code, I'm not seeing a lot of places where links are used that don't actually link to a URL off the page.
