### ISSUE TITLE
Feature: ignore some compliance messages for maintainers

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1240]
### Type of feature

CI

### Current behavior

PR compliance action is messaging everyone, as seen in https://github.com/open-sauced/open-sauced/pull/1239

### Desired solution

add `@open-sauced/maintainers` to the ignore list

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mtfoley** [comment]
Linking https://github.com/mtfoley/pr-compliance-action/issues/35
