### ISSUE TITLE
Bug: Sorting (probably) broken in ListGoals

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/open-sauced#1244]
### Describe the bug

In #1156 when removing lodash dependency we replaced the `sortBy` function. Little typo on the second portion of the ternary on this line: https://github.com/open-sauced/open-sauced/blob/7fb9ca404abb35fecbf105cf40a7fca8eb9bc4eb/src/components/ListGoals.js#L17
When sorting a and b, we needn’t compare b to b.  Haven’t verified on the app but this most likely breaks sorting in the ListGoals component.

### Steps to reproduce

Open app, login if needed
Change sorting field/directions in ListGoals

### Affected services

opensauced.pizza

### Platforms

Desktop, Mobile

### Browsers

Chrome, Firefox, Safari, Edge, Opera

### Environment

Production

### Additional context

I sure hope I haven’t made this typo somewhere else because I’ve written function MANY times ;-)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by murilo-goncalves** [comment]
I will give it a look!
