### ISSUE TITLE
Bug: pr-compliance-action did not fail check on non-compliant title

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/open-sauced#1266]
### Describe the bug

The pr-compliance-action should have failed on the initial title for this PR:

PR: https://github.com/open-sauced/open-sauced/pull/1245
Actions run: https://github.com/open-sauced/open-sauced/runs/3957539987?check_suite_focus=true

You can see the action picked up on the title error, but didn't mark failed.

Linking issue to mtfoley/pr-compliance-action#45

### Steps to reproduce

Submit a PR with a non-compliant title
Action should show as failed check (it doesn't)

### Affected services

opensauced.pizza

### Platforms

Desktop, Mobile

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
I noticed this but was on a roll to get edges everywhere. Definitely interested in the outcome of this!
