### ISSUE TITLE
Bug: Link to contributing guide in the README.md is wrong

### ISSUE THREAD

**Issue by johnyu0424** [open-sauced/open-sauced#1298]
### Describe the bug

The link to contributing guide within 🤝 Contributing section in README.md goes to a page that no longer exists.

PS: While selecting the affected services, I found explore.opensauced.pizza and semantic-release-conventional-config repo have a similar issue, but it wasn't exact, so I didn't added under the affected services.

### Steps to reproduce

1. Go to https://github.com/open-sauced/open-sauced#readme
2. The link to contributing guide within 🤝 Contributing section goes to a page that no longer exists

### Affected services

opensauced.pizza, docs.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnyu0424** [comment]
I am would like to help fix this if someone can let me know if I should make it pointing to https://docs.opensauced.pizza/contributing/introduction-to-contributing/ or https://github.com/open-sauced/.github/blob/main/CONTRIBUTING.md

**Comment by 0-vortex** [comment]
Good catch, It should link to the docs :D feel free to take the issue!

**Comment by johnyu0424** [comment]
.take

**Comment by 0-vortex** [comment]
Yes, following the procedure as it is described in https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues would be the best approach 🍕 

Feel free to add your feedback on the completeness and ease of use of the docs, don't shy away from opening an improvement request if you have a chance!
