### ISSUE TITLE
Feature: Add social card

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1347]
### Type of feature

Feature

### Current behavior

When sharing this site on social, there is no social card

### Desired solution

Set up a social card with the following image. 

![social=image](https://repository-images.githubusercontent.com/71359796/179eca00-061e-11eb-9b57-856a179db1a1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
This is a fun first issue, lots to learn 🍕

**Comment by LevinGar** [comment]
.take

**Comment by kazm41756** [comment]
What's going on

**Comment by RUPAAK** [comment]
Can more pr be made? or is this issue closed?

**Comment by bdougie** [comment]
PR #1347 was closed because it was abandoned. This issue is still ups for grabs. 

Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by RUPAAK** [comment]
.take

**Comment by 0-vortex** [comment]
This is just editing the `index.html` file to add the social card link :D

**Comment by RUPAAK** [comment]
Thankyou. I will create a pr today.....
