### ISSUE TITLE
feat: does pr-compliance-action leave too many comments?

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/open-sauced#1351]
### Discussed in https://github.com/open-sauced/open-sauced/discussions/1350

<div type='discussions-op-text'>

<sup>Originally posted by **mtfoley** December 24, 2021</sup>
For reference see: https://github.com/mtfoley/pr-compliance-action/issues/98

case in point #1348 </div>

There have been several feature releases since v0.2.1 of pr-compliance-action.

In v0.3.0 we use the default branch if protected-branch is not specified.
In v0.4.0, we use secrets.GITHUB_TOKEN if repo-token is not specified.
In v0.5.0, the action is less "chatty" as it uses reviews instead of regular comments and it updates the existing review instead of leaving additional comments.

**Comment by 0-vortex** [comment]
Don't want to troll you but you know you should release v1.0.0 and tag the major at some point right? then we wouldn't have to exact update all the time, we could stick to v1 and only decide if it's important to update when you reach v2 🍕 

With 0 you are making it harder for us to maintain and can wrongly assess your action is not "ready" for production :D

**Comment by 0-vortex** [comment]
> Don't want to troll you but you know you should release v1.0.0 and tag the major at some point right? then we wouldn't have to exact update all the time, we could stick to v1 and only decide if it's important to update when you reach v2 🍕
> 
> With 0 you are making it harder for us to maintain and can wrongly assess your action is not "ready" for production :D

You can use this example to do it with only 2 clicks/release - unless you manual draft/release, then it triggers automatically

**Comment by mtfoley** [comment]
> Don't want to troll you but you know you should release v1.0.0 and tag the major at some point right? then we wouldn't have to exact update all the time, we could stick to v1 and only decide if it's important to update when you reach v2 🍕
> 
> With 0 you are making it harder for us to maintain and can wrongly assess your action is not "ready" for production :D

I want to see how it does with v0.5.0. After fixing any kinks, I'll go to v1.0.0.

**Comment by mtfoley** [comment]
@0-vortex i cut v1.0.0 today
