### ISSUE TITLE
Feature: remove the notes box. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1401]
### Type of feature

🍕 Feature

### Current behavior

The notes box is extremely buggy and will need to be removed for now. This project is undergoing a lot of updates and this is not needed for now. 

![Group 1 (1)](https://user-images.githubusercontent.com/5713670/161272843-79715b34-13b6-4b8d-9b9d-6def05a73ba6.png)

### Suggested solution

Remove all the notes box and all dependencies. 

### Additional context

This PR will also close https://github.com/open-sauced/open-sauced/pull/1201

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
.take
