### ISSUE TITLE
Feature: Design system and UI should match hot open sauced.pizza. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1403]
### Type of feature

🍕 Feature

### Current behavior

Today the Open Sauced UI is stylistically different from https://hot.opensauced.pizza. As we are preparing the new design, we should consider match some of the modern design elements. 

 

### Suggested solution

- [ ] Match (padding) spacing for the body content. this can be done easily with the Wrapper component in the styles folder. 
- [ ] Match Card UI elements, i.e. border-radius, text.  
-  Anything else

https://design.opensauced.pizza is all managed in the storybook folder

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by mtfoley** [comment]
Just posting for some reference, here are some of the utility classes in use on hot repo:
repo cards:

container:
```html
container grid xs:grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 max-w-screen-xl mx-auto auto-rows-fr
```
repo card:
```html
<div class="bg-offWhite rounded-xl pt-6 px-4 pb-2 font-roboto"`>...</div>
```

Looks like the repo card headings use `text-xl` utility class.
