### ISSUE TITLE
Feature: New usable UI 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1404]
### Type of feature

🍕 Feature

### Current behavior

Today open sauced shares too much context without context. Working with UI/UX designer and fixing up current screens. 

### Suggested solution

![Screen Shot 2022-04-01 at 2 45 56 PM](https://user-images.githubusercontent.com/5713670/161345584-85ac4524-131e-4151-9ea8-bd05a9b4df43.png)

The only thing not available in a component is the "similar repos"

Feel free to tack this in separate issues. 
- [ ] Similar Repos
- [ ] Contributors section
- [ ] Context Card to include more data

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by mtfoley** [comment]
re: similar repos feature, I wonder if similarity could be based on topic and/or language.
For example, if I run this query on Open-Sauced, I get TypeScript and JavaScript as languages and "open-source" and "graphql" as topics:
```graphql
query FetchUserForkCount($repoName: String!, $repoOwner: String!) {
  gitHub {
    repository(name: $repoName, owner: $repoOwner) {
      hasIssuesEnabled
      repositoryTopics(first: 2) {
        nodes {
          topic {
            name
          }
        }
      }
      languages(first: 2, orderBy: {field: SIZE, direction: DESC}) {
        edges {
          node {
            name
          }
        }
      }
    }
  }
}
```

Using only all four together and searching in GitHub gives me 26 results.
https://github.com/search?q=topic%3Agraphql+topic%3Aopen-source+language%3AJavaScript+language%3ATypeScript&type=Repositories

**Comment by bdougie** [comment]
This work was moved to open-sauced/insights
