### ISSUE TITLE
Feature: Copy hot.opensauced.pizza footer

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1408]
### Type of feature

🍕 Feature

### Current behavior

![Screen Shot 2022-04-01 at 3 31 27 PM](https://user-images.githubusercontent.com/5713670/161350362-c2dbc9be-0fcb-41f3-be53-aee5e650cb0d.png)

We should remove external links and place them in the footer. 

### Suggested solution

![Screen Shot 2022-04-01 at 3 30 49 PM](https://user-images.githubusercontent.com/5713670/161350369-39b56034-0ce9-4263-a35b-cb49fa09dd28.png)

Copy the footer from https://github.com/open-sauced/hot

### Additional context

You can replace this footer.
![Screen Shot 2022-04-01 at 3 37 02 PM](https://user-images.githubusercontent.com/5713670/161350790-9497f1b1-cc60-4e8c-8279-f7aa869192f6.png)

https://github.com/open-sauced/open-sauced/blob/main/src/styles/Footer.jsx

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
.take
