### ISSUE TITLE
Feature: Add the new theme switch to the storybook

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1419]
### Type of feature

🍕 Feature

### Current behavior

The new theme switch is now live in the nav bar, but it is not reflected in the storybook. 

### Suggested solution

https://design.opensauced.pizza/?path=/story/nav--home-page

1. Update the Nav to reflect the live nav on https://app.opensauced.pizza
2. Remove extra nav items.

### Additional context

https://github.com/open-sauced/open-sauced/pull/1417

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by chadstewart** [comment]
I just realized that I didn't mention that I added the Radix Switch to Storybook. My apologies for that. Should I add screenshots to the original PR or to this new issue?

**Comment by bdougie** [comment]
This is fixed. Just had the wrong site pointing to design.opensauced.pizza
