### ISSUE TITLE
Bug: Weird spacing on the dashboard and repository screens

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1422]
### Describe the bug

![Screen Shot 2022-04-13 at 2 52 22 PM](https://user-images.githubusercontent.com/5713670/163276521-4c4de68c-95f6-41b0-861b-20f3f27ffa8d.png)
![Screen Shot 2022-04-13 at 2 52 18 PM](https://user-images.githubusercontent.com/5713670/163276524-565f05ac-e893-42c2-98ea-82eaa036e949.png)

The left and right margin seem too much. this should match the top margin.

### Steps to reproduce

Visit the dashboard as a logged in user.

### Affected services

opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ginona** [comment]
Hey, can you assign this to me? I will fix it

**Comment by bdougie** [comment]
Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by ginona** [comment]
.take

**Comment by TAKANOME-DEV** [comment]
Hey @ginona any updates on this issue?

**Comment by 0-vortex** [comment]
Clear for the taking again 🍕

**Comment by TAKANOME-DEV** [comment]
.take
