### ISSUE TITLE
Feature: Remove url dependency for issue number

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1424]
### Type of feature

🍕 Feature

### Current behavior

When visiting a repository it is required to have the goal issue number in the url. I would like to remove that so anyone can view any repo. 

### Suggested solution

Remove :id here https://github.com/open-sauced/open-sauced/blob/main/src/containers/Dashboard.jsx#L11

Also watch for tests to not fail. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nworiekingslee** [comment]
.take

**Comment by bdougie** [comment]
Most of the changes for this is deleting places where we look for the issue id from the open-sauced-goals rep. 

Just notice that this line and dependencies should be deleted - https://github.com/open-sauced/open-sauced/blob/main/src/components/Repository.jsx#L61-L62

**Comment by 0-vortex** [comment]
> Most of the changes for this is deleting places where we look for the issue id from the open-sauced-goals rep.
> 
> Just notice that this line and dependencies should be deleted - https://github.com/open-sauced/open-sauced/blob/main/src/components/Repository.jsx#L61-L62

Good catch!

**Comment by mtfoley** [comment]
@nworiekingslee it's been about 2 weeks since you had assigned yourself to this one and I was curious about it so I took a crack at it. Take a look at what I've done and let me know if it makes sense to you:
https://github.com/mtfoley/open-sauced/commit/deb8db6c54a53ad529769fd314cd519b263d5a60

@bdougie I can do a PR for this if you'd like. Test suite still seemed to pass and it looks like the test for Repository only checks to make sure the Fork button is hidden by default.

**Comment by nworiekingslee** [comment]
Ok @mtfoley, I am checking it out

**Comment by nworiekingslee** [comment]
> @nworiekingslee it's been about 2 weeks since you had assigned yourself to this one and I was curious about it so I took a crack at it. Take a look at what I've done and let me know if it makes sense to you: [mtfoley@deb8db6](https://github.com/mtfoley/open-sauced/commit/deb8db6c54a53ad529769fd314cd519b263d5a60)
> 
> @bdougie I can do a PR for this if you'd like. Test suite still seemed to pass and it looks like the test for Repository only checks to make sure the Fork button is hidden by default.

Also, I apologize for the delay. I am new to the project, needed some extra time to get familiar with the code.

**Comment by nworiekingslee** [comment]
> @nworiekingslee it's been about 2 weeks since you had assigned yourself to this one and I was curious about it so I took a crack at it. Take a look at what I've done and let me know if it makes sense to you: [mtfoley@deb8db6](https://github.com/mtfoley/open-sauced/commit/deb8db6c54a53ad529769fd314cd519b263d5a60)
> 
> @bdougie I can do a PR for this if you'd like. Test suite still seemed to pass and it looks like the test for Repository only checks to make sure the Fork button is hidden by default.

The issue number still appear on the URL

**Comment by nworiekingslee** [comment]
I am beginning to worry that I didn't understand the issue.

Here's what I have done. https://github.com/nworiekingslee/open-sauced/commit/e9c434395e296e92b506ec38fba54c995e2812da

I edited App.jsx, Dashboard.jsx and List Goals.jsx

**Comment by mtfoley** [comment]
> The issue number still appear on the URL

you’re exactly right, we need to change this line as well, and probably some supporting parts:
https://github.com/open-sauced/open-sauced/blob/32178a523c3e41346c8c93878f6b01318908b1e2/src/components/ListGoals.jsx#L96

**Comment by mtfoley** [comment]
ok @nworiekingslee, I made the changes to ListGoals that you pointed out. I'm going to assign this issue to myself and add you as a reviewer to a PR.  Let me know if it works any better for you.

**Comment by nworiekingslee** [comment]
Thank you @mtfoley
