### ISSUE TITLE
Feature: storybook vite

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#1429]
### Type of feature

🍕 Feature

### Current behavior

storybook uses webpack

### Suggested solution

https://github.com/Bedrock-Layouts/Bedrock mic drop

### Additional context

Not a good first issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Hi @0-vortex! I know this needs triage, but am wondering the scope of this is. Is Bedrock just an example for inspiration or are you looking for more for Storybook from something in Bedrock? Or is it just porting the bundling to vite for Storybook? 

If so I got that up and running pretty quickly if folks are interested, https://github.com/nickytonline/open-sauced/tree/migrate-storybook-to-vite. Happy to PR this up.

**Comment by 0-vortex** [comment]
> Hi @0-vortex! I know this needs triage, but am wondering the scope of this is. Is Bedrock just an example for inspiration or are you looking for more for Storybook from something in Bedrock? Or is it just porting the bundling to vite for Storybook?
> 
> If so I got that up and running pretty quickly if folks are interested, https://github.com/nickytonline/open-sauced/tree/migrate-storybook-to-vite. Happy to PR this up.

When I opened the issue the vite build wasn't fully released, would be great if you could PR this upstream! 🍕 ❤️

**Comment by nickytonline** [comment]
Cool cool. Mind assigning this to me? I'll PR it up.
