### ISSUE TITLE
Bug: Posthog not sending analytics data

### ISSUE THREAD

**Issue by chadstewart** [open-sauced/open-sauced#1440]
### Describe the bug

Open sauced will not send analytics data to posthog once deployed.

### Steps to reproduce

Run the application, click on the login button and then click on both onboarding butons in the onboarding flow.

### Affected services

opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
.take
