### ISSUE TITLE
Bug: When adding brob/plug11ty.com "not valid" error

### ISSUE THREAD

**Issue by brob** [open-sauced/open-sauced#1451]
### Describe the bug

When adding a repository from my synced GitHub account, I get the message "Invalid GitHub repository"

### Steps to reproduce

1. Go to https://app.opensauced.pizza/
2. In `owner/repo` field type brob/plug11ty.com (corresponds to [this repo](https://github.com/brob/plug11ty.com))
3. Click "Add"
4. Error message "Invalid GitHub repository" appears

### Affected services

opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by mtfoley** [comment]
I haven't reproduced yet, but here is the code path I suspect is responsible:

Repo Form checking validity:
https://github.com/open-sauced/open-sauced/blob/4a26b94eaa1a1094ee0dd0d7ca76ead50da2acc4/src/components/AddRepoForm.jsx#L23

Validity Checker catching `.com` and assuming this is an absolute URL:
https://github.com/open-sauced/open-sauced/blob/4a26b94eaa1a1094ee0dd0d7ca76ead50da2acc4/src/lib/util.js#L5

From there, I haven't validated, but I believe the intention would be for us to consider this a "relative URL".

**Comment by 0-vortex** [comment]
> I haven't reproduced yet, but here is the code path I suspect is responsible:
> 
> Repo Form checking validity:
> 
> https://github.com/open-sauced/open-sauced/blob/4a26b94eaa1a1094ee0dd0d7ca76ead50da2acc4/src/components/AddRepoForm.jsx#L23
> 
> Validity Checker catching `.com` and assuming this is an absolute URL:
> 
> https://github.com/open-sauced/open-sauced/blob/4a26b94eaa1a1094ee0dd0d7ca76ead50da2acc4/src/lib/util.js#L5
> 
> From there, I haven't validated, but I believe the intention would be for us to consider this a "relative URL".
<img width="446" alt="Screenshot 2022-06-10 at 16 48 10" src="https://user-images.githubusercontent.com/237133/173079843-194ce19d-eebc-4b49-8965-70a78068bbe7.png">

Needs a fix for sure :D

**Comment by mtfoley** [comment]
my gut tells me that this would be a sufficient check:
```js
const isRelativeUrl = !(url.substr(0,7) === 'http://' || url.substr(0,8) === 'https://');
```
The upsides to this would be:
- we don't try to get too clever with regex
- we don't try to anticipate all of the TLDs

Test suite would need adjustment too.
https://github.com/open-sauced/open-sauced/blob/4a26b94eaa1a1094ee0dd0d7ca76ead50da2acc4/src/tests/util.test.js

**Comment by mtfoley** [comment]
Marking this as a good first issue - I think there's enough context to work with.

**Comment by mtfoley** [comment]
For what it's worth, this repo is flagged as invalid, for similar reasons:
https://github.com/httpie/httpie

**Comment by arth2002** [comment]
I want to work on this issue, please assign me

**Comment by bdougie** [comment]
Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by arth2002** [comment]
.take

**Comment by arth2002** [comment]
@mtfoley my test cases are not getting cleared. I am not getting it what changes I need to do in https://github.com/open-sauced/open-sauced/blob/4a26b94eaa1a1094ee0dd0d7ca76ead50da2acc4/src/tests/util.test.js
so can you please me through this process? 
I am a newbie in this open-source contributions

**Comment by 0-vortex** [comment]
> @mtfoley my test cases are not getting cleared. I am not getting what changes I need to do in https://github.com/open-sauced/open-sauced/blob/4a26b94eaa1a1094ee0dd0d7ca76ead50da2acc4/src/tests/util.test.js
> although brob/plug11ty.com is valid to add but test cases are getting failed.
> so can you please me through this process?
> I am a newbie in this open-source contributions

Hey, I don't see you having forked the open-sauced repo, once you do, you can apply the fixes discussed above. There is nothing you need to do to the unit test, it's the code that this issue requires fixing. 

If that is not the case IE you are not looking to contribute, let us know and we will assign to someone else :D

**Comment by arth2002** [comment]
I made a PR
Please check it out
