### ISSUE TITLE
Bug: Fork button doesn't know I already have a fork

### ISSUE THREAD

**Issue by olearycrew** [open-sauced/open-sauced#1454]
### Describe the bug

When adding a project you already have a fork of, open-sauced doesn't recognize that there is a fork.  After clicking fork, it then knows there is a fork but doesn't "remember" that when you come back to the project

### Steps to reproduce

1. Sign up for open-sauced
2. Add a repo that you already have a fork of (I added `Lissy93/dashy` which I already have a fork of at: https://github.com/olearycrew/dashy)
3. On the project page, observe that open-sauced thinks the fork doesn't exist:

![image](https://user-images.githubusercontent.com/6044920/176253867-f357bdc1-32d3-4aa5-81cf-06ef811a1403.png)

Now, when I click fork it _then_ figures out that one exists and says "View fork"

![image](https://user-images.githubusercontent.com/6044920/176254172-0f56bb3a-d211-44cb-a4e8-963fac490989.png)

But that doesn't persist when I come back to the project page.

### Affected services

opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by mtfoley** [comment]
Thanks for adding this issue! For what it's worth, the code related to this component is in this file:
https://github.com/open-sauced/open-sauced/blob/main/src/components/Repository.jsx

**Comment by mtfoley** [comment]
@bdougie I suspect that the issue here is that the persisted query in use is tied to your identity on GitHub.  When I open repos that I know we both have forks for, I get the "View Fork" button (e.g. Team-TAU/tau). When I open repos that I know you have a fork for, but I don't, I still see the "View Fork" button (e.g. open-sauced/beybot).

**Comment by bdougie** [comment]
The bug that keeps on giving. My hope is that we can revamp a lot of these interactions and make them less buggy while I am focusing on this full-time this summer.

**Comment by mtfoley** [comment]
I was looking at a fix for this, and I feel I stumbled on a GitHub GraphQL bug. We have some unused code at https://github.com/open-sauced/open-sauced/blob/main/src/lib/apiGraphQL.js#L375 that is *not* a persisted query.  When I switch the Repository.jsx file to use this query instead, I get a "Resource Not Accessible" error from OneGraph. You can verify this on https://explore.opensauced.pizza/ by choosing the "FetchUserForkCount" in the query dropdown menu.  Right now that query is:
```graphql
query FetchUserForkCount(
  $repoName: String!
  $repoOwner: String!
) {
  gitHub {
    repository(name: $repoName, owner: $repoOwner) {
      forks(affiliations: OWNER) {
        totalCount
      }
    }
  }
}
```

If I add the privacy parameter, I don't get an error anymore, but the now the total count is > 1 even though I'm specifying that only forks owned by the logged in user should be counted. 
```graphql
query FetchUserForkCount($repoName: String!, $repoOwner: String!) {
  gitHub {
    repository(name: $repoName, owner: $repoOwner) {
      forks(affiliations: OWNER, privacy: PUBLIC) {
        totalCount
      }
    }
  }
}

```

If I run this query for `Team-TAU/tau`, it lists 30 forks.
![Screen Shot 2022-08-27 at 10 58 50 PM](https://user-images.githubusercontent.com/3792749/187055533-33ddaa4a-dfe3-4e1e-8241-07aab30de0c3.png)

Again, to me this feels like a bug in GitHub GraphQL API.

**Comment by mtfoley** [comment]
As a follow-up, this query might be something we can use, but it'll be hitting Github search fairly often.

```gql
query MyQuery {
  gitHub {
    search(first: 10, query: "user:@me fork:only \"[repoName]\" in:name", type: REPOSITORY) {
      edges {
        node {
          ... on GitHubRepository {
            id
            name
            parent {
              nameWithOwner
            }
          }
        }
      }
    }
  }
}

```

This gives me a couple of results and I can use the parent -> nameWithOwner to verify it's actually a fork of the repo I'm interested in.
