### ISSUE TITLE
Bug: added the same repo twice to my app.opensauced.pizza dashboard

### ISSUE THREAD

**Issue by davidalpert** [open-sauced/open-sauced#1462]
### Describe the bug

Somehow I managed to add a repo to my Dashboard twice (I think I clicked "Add" twice before I saw the repo show up); now I have two instances of that `go-task/task` repo appearing in my dashboard and I cannot see any way to remove one.

### Steps to reproduce

1. Go to the Dashboard view (https://app.opensauced.pizza/#)
1. Type in a new repo to add (e.g. `go-task/task`) and click "Add" twice

Expected result
- the new repo is added once

Actual result
- the new repo is added twice

### Affected services

app.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by mfoley-sas** [comment]
@davidalpert thanks for filing this! There once was a button to remove goals but it was factored out as part of work in other repos.  In any case, a workaround you can use to remove the goal is to open your goals repository close the underlying issue. If you look in the issues list in this repo (https://github.com/davidalpert/open-sauced-goals/issues), you should be able to see issues with titles that correspond to the repos you added. If you close one of these issues, then things should be how you want them to be.

**Comment by cameronldroberts** [comment]
Sounds like a dup of this issue - https://github.com/open-sauced/open-sauced/issues/1460

I had a quick look and I think it just needs some code to stop submitting the form twice in quick succession. There’s already code to handle the repo already existing [here](https://github.com/open-sauced/open-sauced/blob/main/src/components/AddRepoForm.jsx#L33). I think by hitting the button twice in quick succession we’re getting beyond this check as the repo might not be officially added yet.
