### ISSUE TITLE
Bug: github-actions bot has outdated link for Contributing Guide

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/open-sauced#1466]
### Describe the bug

The automated github bot usually posts comments on PRs to notify their makers if they need to edit some stuff. Example: 
![firefox_Fll84kM9Gg](https://user-images.githubusercontent.com/52013393/194600841-7f6f5f1a-93c3-4caf-9b4c-4b29c84bc594.png)

However, the "Contributing Guide" has an outdated link, that is 404 now. This should be fixed

The correct link would be: https://docs.opensauced.pizza/contributing/introduction-to-contributing/

What needs to be done: Replace the old link with this correct link.

### Steps to reproduce

1. Go to this PR https://github.com/open-sauced/open-sauced/pull/1465
2. Click on "Contributing Guide" in the bot's comment

### Affected services

opensauced.pizza

### Platforms

Desktop

### Browsers

Firefox

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Good catch! 👍

**Comment by RozzaysRed** [comment]
.take
