### ISSUE TITLE
Bug: An error occurs when attempting to load admin status

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/open-sauced#1474]
### Describe the bug

The website prints an error in console that originates from the function that is responsible for loading the "admin" status for the logged in user.
screenshot of the console error:
![image](https://user-images.githubusercontent.com/52013393/202018080-f9eeb0fb-45ba-43a2-b1a8-73daaef2a887.png)

screenshot of the code where it originated from:
![image](https://user-images.githubusercontent.com/52013393/202018197-e557450f-cd42-457a-8bdf-f9494c7d7c70.png)
It is in src/index, line 68

This issue occurs because the input object `res` actually fails to retrieve the data expected, this is the content of the `res` object: 
![image](https://user-images.githubusercontent.com/52013393/202018447-2b20bb9e-e4a1-4d33-a010-189ad16edbfb.png)

### Steps to reproduce

1. Goto app.opensource.com
2. Login
3. Open console

### Affected services

opensauced.pizza

### Platforms

Desktop

### Browsers

Firefox, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by AhnafSulficar** [comment]
.take
