### ISSUE TITLE
Feature: OpenSauced the final form

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#1487]
### Type of feature

🍕 Feature

### Current behavior

OneGraph shut down operations on the 31st of March. We need to deprecate this project.

<img width="1552" alt="Screen Shot 2023-04-05 at 3 50 41 PM" src="https://user-images.githubusercontent.com/5713670/230208625-8eb44deb-aa2a-452c-9c68-7a4a40a274ae.png">

### Suggested solution

1. Archive the repo.
2. Redirect to opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
IMHO archive the app, plan a v2 for the repo, keep the stars, all the traction and the centralised workflows 🍕

**Comment by bdougie** [comment]
> IMHO archive the app, plan a v2 for the repo, keep the stars, all the traction and the centralised workflows 🍕 

Agree. Updated the title.

My suggestion is a static site that shares links to things we want people to find.
