### ISSUE TITLE
Bug:  Cannot login to Github With Firefox or Brave

### ISSUE THREAD

**Issue by jlangson** [open-sauced/open-sauced#1492]
### Describe the bug

When I click "login with github" using firefox, I get this error message

SyntaxError: JSON.parse: expected property name or '}' at line 1 column 2 of the JSON data

When I try on Brave I get this error message "{errors: [{"message": "OneGraph has reached its end of life."}]}"

### Steps to reproduce

1. Go to https://app.opensauced.pizza/
2. Click "login with github"
3. Get error message

### Affected services

opensauced.pizza

### Platforms

Desktop

### Browsers

Firefox, Other (add additional context)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This planned for archival and all future work is being moved to https://github.com/open-sauced/insights
