### ISSUE TITLE
List user pull request contributions per repo.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#453]
## Story

As a user, I would like to see a list of my active/inactive code contributions for a particular repo in the last 6 months.

Code Contributions can be identified as: pull requests merged, open, closed see note below

## Background
This was originally scoped in #451 but split off after discovering an API limitation where Pull Requests are not filterable.

There is a way to use the Search endpoint for PRs.

```
search(first: 10, query: "repo:bdougie/open-sauced author:bdougie is:open", type: ISSUE) {
      edges {
        node {
          ... on GitHubPullRequest {
            id
            title
            url
            number
            state
          }
        }
      }
    }
```

**Comment by yg** [comment]
I think [github/tab-container-element](https://github.com/github/tab-container-element) will be suitable to shows issues and PRs in tabs.

![Screenshot](https://user-images.githubusercontent.com/61746440/85921588-d8344500-b89a-11ea-9a37-7266ed0123cd.png)

Here is another example: https://codepen.io/VoloshchenkoAl/pen/dMWxoL

**Comment by filiptronicek** [comment]
Should we lazy load this tab or load everything at the same time? @yg @bdougie

**Comment by bdougie** [comment]
Yeah, I am open to suggestions on how to handle that. My assumption is there are react libraries that handle that. It has been a while since I built something with tabs. I can put some thought into this after the next release.

**Comment by filiptronicek** [comment]
I'm currently trying to put something together, I'll keep you all updated.

**Comment by notBdougie** [comment]
.take

**Comment by usoni11** [comment]
@filiptronicek  @bdougie Hi, I am new here! And I would want to take up this. I think we can show a card below the Issues Card for oper PRs.

**Comment by filiptronicek** [comment]
Hi @usoni11, if you'd like to be assigned to this issue, you can follow the steps in the contribution guidelines:

https://github.com/open-sauced/open-sauced/blob/main/CONTRIBUTING.md

**Comment by usoni11** [comment]
.take

**Comment by bdougie** [comment]
@usoni11, I look forward to seeing what you come up with. This feature is slightly open-ended, but feel free to join our Discord as well. You can find me there and I can answer any questions you may have.

https://discord.com/invite/gZMKK5q

**Comment by misss-popcorn** [comment]
Sure, thank you  :)

**Comment by bdougie** [comment]
Focusing on #344. Removing contribution focused features
