### ISSUE TITLE
Add filtering for issues by labels

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#456]
![Screenshot 2020-01-24 13 07 31](https://user-images.githubusercontent.com/5713670/73104126-87af5a80-3eaa-11ea-8f4b-379421a70843.png)

**Comment by bdougie** [comment]
UI Mock, open to other ideas. The thought is at least filtering by "good-first-issues" and similar. 

<img width="135" alt="Screenshot 2020-06-09 15 54 02" src="https://user-images.githubusercontent.com/5713670/84208873-936e7880-aa69-11ea-84e5-b2575fb4614d.png">


The idea to track the number of issues by filter. 

<img width="736" alt="Screenshot 2020-06-09 15 49 57" src="https://user-images.githubusercontent.com/5713670/84208881-98cbc300-aa69-11ea-863a-14634805ee14.png">

**Comment by kunal1244** [comment]
@bdougie Maybe add a issue search too?  
Also, the panels do not include the issue number and pull requests associated as of now. Should we add those as well?

**Comment by bdougie** [comment]
Search would be nice to have, but it is not in the scope of this feature.

Reasons why I am not interested in search:
- searching issues can easily be done on GitHub. We should be focusing on enhancing the contributor experience and not recreating. 
- searching can be buggy if not implemented well. This will also be an expensive API call and not worth the cost. 
- filter and searching by a label is preferred and could be a compromise to not having search. 

Happy to hear counterpoints, if I am wrong, I am also happy to have an issue opened to discuss how to implement in the least cost-effective way without degrading the current user experience.

**Comment by kunal1244** [comment]
Makes sense, it would definitely come with a lot of unnecessary API calls and be expensive in general. Will try to come up with a better way to implement this.

What about the WIP issues with merged Pull Requests and Issue number features, though? I think these are essential features, which help in keeping track of workable issues. Does this need a separate issue?

**Comment by bdougie** [comment]
I think you are adding some good context to this feature. I still the essential feature would be filtering by labels. Perhaps the first version of this feature is filtering by "assigned" or "unassigned" and a select list of label ["good first issue", "documentation", "help wanted"]

**Comment by kunal1244** [comment]
@bdougie Yeah, I totally got your argument about filtering by labels. If I understood this correctly, adding filters other than labels is not part of this version, and can be implemented going forward by thinking of a least-cost approach.

Displaying associated PRs and the corresponding ID of issues in the issue panels, alongside the number of comments and assigned users (which are already present) in the dashboard is what I'm talking about. These are mutually exclusive with this filter feature. Do you think these are good additions? 

Correct me if I'm missing something here.

**Comment by bdougie** [comment]
Yes, I am a fan of including this data. Feel free to open up a separate issue so we can discuss it further. Once its opened, I'd be happy to see PR or mockup.

**Comment by mtfoley** [comment]
@bdougie I have been playing with the openGraph queries in src/lib/apiGraphQL.js to see if I could get this filtering to work according to the `issues` field, `labels` argument here: https://docs.github.com/en/graphql/reference/objects#repository. Unfortunately the requests return an object with the error "Resource not accessible by integration". I think this got mentioned in an issue or PR somewhere but I can't find that at the moment. I'd love to take a crack at this issue but I think this error would need to be looked at first.  I had modified the code to use a dynamic query "IssuesQuery" instead of a predefined doc, so it's not technically an issue with the codebase.

**Comment by bdougie** [comment]
The authentication only provides access to your goals repo. I will need provide an endpoint for that in the, i.e. https://github.com/open-sauced/open-sauced/blob/main/src/lib/persistedGraphQL.js.

These are authenticated requests to the GitHub API. Do you have an example of the GraphQL you are looking to get data from?

**Comment by mtfoley** [comment]
Ok, I don't have a lot of experience with GraphQL, but I think it'd be something like what's in [https://github.com/open-sauced/open-sauced/blob/main/src/lib/apiGraphQL.js](https://github.com/open-sauced/open-sauced/blob/main/src/lib/apiGraphQL.js) for the query "IssuesQuery", except with the labels limiting as discussed above. So I think it'd be like this:
```
  query IssuesByLabelQuery($owner: String!, $repo: String!) {
    gitHub {
      repositoryOwner(login: $owner) {
        repository(name: $repo) {
          hasIssuesEnabled
          issues(first: 5, states: OPEN, labels: ["needs help", "documentation", "good first issue"], orderBy: {field: CREATED_AT, direction: DESC}) {
            totalCount
            data: edges {
              cursor
              node {
                id
                title
                url
                state
                author {
                  login
                }
                labels(first: 5) {
                  data: edges {
                    node {
                      id
                      name
                      color
                    }
                  }
                }
                comments {
                  totalCount
                }
                milestone {
                  title
                }
                participants(first: 3) {
                  totalCount
                  nodes {
                    login
                    avatarUrl
                  }
                }
                createdAt
              }
            }
          }
        }
      }
    }
  }
```

**Comment by bdougie** [comment]
you can now use the `persistedIssuesByLabelFetch` query.

**Comment by mtfoley** [comment]
.take
