### ISSUE TITLE
Wrong stars count in homepage

### ISSUE THREAD

**Issue by yg** [open-sauced/open-sauced#526]
![Screenshot](https://user-images.githubusercontent.com/61746440/82065335-9afd6480-96eb-11ea-8ab8-f2c3a402ec20.png)

**Comment by bdougie** [comment]
This is known, at least by me. I have not figured out a way to get that data on this page yet. 

I think this will be solved with this https://github.com/bdougie/open-sauced/issues/384

**Comment by bdougie** [comment]
This will be fixed when #616 is merged.
