### ISSUE TITLE
Better error message when GitHub API in down. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#531]
<img width="1392" alt="Screenshot 2020-05-22 15 40 27" src="https://user-images.githubusercontent.com/5713670/82714247-9e8c7080-9c42-11ea-801d-89f890d17fad.png">

**Comment by yg** [comment]
@bdougie How we are going to simulate the API that looks like down?

![](https://media0.giphy.com/media/l0LIYv9tJFIVHxF5u/giphy.gif)

**Comment by bdougie** [comment]
If this this app was using the REST api I would say GitHub.com/nock/nock but I am not sure if it handles graphql mocking as well. Something to look into.

**Comment by bdougie** [comment]
I learned of https://miragejs.com/ and think it would make for a better tool to mock out the GitHub API.

**Comment by 0-vortex** [comment]
Is this still desirable ? Could we document a way to reproduce the error for better development ?

**Comment by bdougie** [comment]
Taking a look, but my I remembered this existed perhaps there is a more naive approach to this that we could apply. https://github.com/marketplace/actions/github-status
