### ISSUE TITLE
[Onboarding] Can't log in when developing locally

### ISSUE THREAD

**Issue by Brawrdon** [open-sauced/open-sauced#556]
### Describe the bug

I've just attempted to work on development locally but I'm unable to log in. The GitHub login window appears, it seems to work, but then it dissapears and nothing happens.

### To Reproduce

1. Clone the repo
2. run `npm install`
3. run `npm start`
4. Visit localhost:3000 and attempt to log in
5. Nada

### Desktop

- OS: macOS 10.15.4
- Browser: Firefox
- Version: 76.0.1

### Additional context

I know onboarding is something to be looked at but I thought I should still note this down!

**Comment by Brawrdon** [comment]
Just checked the console and it seems to be an issue with CORS headers not matching those expected by OneGraph's OAuth: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://serve.onegraph.com/oauth/code?app_id=...[Omitted]... (Reason: CORS header 'Access-Control-Allow-Origin' does not match 'https://localhost:3000').`

**Comment by bdougie** [comment]
That is weird. The localhost is allowlisted. Are you able to do a refresh with a cache? Does work then?

**Comment by Brawrdon** [comment]
I just tried it with Chrome, seems to be a Firefox specific issue.

**Comment by yg** [comment]
@bdougie Let me try in [BrowserStack](https://browserstack.com) in the following browsers

- [ ] Safari 13.1
- [ ] Firefox 76
- [ ] Chrome 83
- [ ] Opera 68
- [ ] Edge 81

**Comment by yg** [comment]
@Brawrdon @bdougie I tested in all browsers listed above, it is working as expected!

Can you confirm the browser version @Brawrdon

**Comment by Brawrdon** [comment]
76.0.1. The issue is still happening with a fresh clone and force clearing the cache.

**Comment by yg** [comment]
@Brawrdon It's weird! Can you possibly try a screen record and share it?

If you don't have one, I recommend Loom https://chrome.google.com/webstore/detail/loom-for-chrome/liecbddmkiiihnedobmlmillhodjkdmb

**Comment by bdougie** [comment]
@open-sauced/triage can I get more eyes on this to see if this is reproducible?

**Comment by kunal1244** [comment]
@Brawrdon I was facing the same issue. Took a pull from upstream and it worked out. Try this and let us know?
P.S. Make sure you remove node_modules, clear npm cache, and run install again.

**Comment by Brawrdon** [comment]
Okay I figured out what the issue was on my end... I have the Firefox extension [HTTPS Everywhere](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/) installed and so I can only assume it was using **https**://localhost:3000 as the origin instead of **http**. Disabling the extension fixes the problem!

I realised this was probably the issue because I had a problem connecting to a development environment during my virtual assessment day which was caused by that extension 🤣
