### ISSUE TITLE
No 404 Page

### ISSUE THREAD

**Issue by yg** [open-sauced/open-sauced#570]
### Describe the bug

No **404** Page

### To Reproduce

Visit https://opensauced.pizza/oops

### Expected behavior

Show 404 Page

**Comment by bdougie** [comment]
I did the initial work to get the unstyled 404 pages and realized that #525 is blocking this since the JWT is reset when refreshed, causing the 404 to be rendered as well.

**Comment by bdougie** [comment]
#598 has unblocked this. I will begin work on this, this afternoon.

**Comment by yg** [comment]
Good to hear @bdougie, It seems like we are fixing many bugs and shipping some good features!
