### ISSUE TITLE
iPad UI is not responsive

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#579]
### Screenshots

![image](https://user-images.githubusercontent.com/5713670/83287128-f9b7e900-a195-11ea-8d0d-6d8e7e691696.png)
![image](https://user-images.githubusercontent.com/5713670/83287142-ffadca00-a195-11ea-97ca-755c96414afa.png)

### Smartphone

- Device: IPad Pro 10.5 inch
- OS: iOS 
- Browser: safari
- Version: 13.4.1

### Additional context

The pizza needs a “space between”
The quotes need to be center and on their own row

**Comment by bdougie** [comment]
#588

**Comment by filiptronicek** [comment]
I'm not sure about whether this update is already on the website, but I still have issues when being between 769 and 1069 px in width.
![image](https://user-images.githubusercontent.com/29888641/83734548-7132c000-a64f-11ea-9943-5483101dc454.png)

**Comment by yg** [comment]
@filiptronicek I think this feature is not shipped to production.

**Comment by bdougie** [comment]
@filiptronicek thanks for point that out. I think we will need to start shipping bug fixes to the production right away. I am going to ship v0.14.0 a day earlier and moving forward make sure cut patch releases when a bug is fixed.
