### ISSUE TITLE
Including spaces before or after repo name adds an item to the list

### ISSUE THREAD

**Issue by Brawrdon** [open-sauced/open-sauced#580]
### Describe the bug

When adding a space before or after the input when trying to add a repository results in the item being added to the list. When clicking the item it opens a page that display loading spinner indefinitely with no "not found" error. I noticed this when trying to paste a copy the owner/repo text from the repo's page, the pasted text included spaces which I forget to remove from the end. Adding repos like this **might** be a common method for users and they might also forget to remove the trailing space.

### To Reproduce
1. Enter the **correct** name of a repo
2. Include a space before and or after the repo
3. Watch as the repo is added

### Expected behavior
An error message should be displayed and the item should not be added to the list.

### Screenshots

![Evidence of erroneous repo in list](https://user-images.githubusercontent.com/9751243/83289115-74a3f280-a1dc-11ea-8949-b2f7811a7007.png)

![Evidence of erroneous repo URL](https://user-images.githubusercontent.com/9751243/83289613-38bd5d00-a1dd-11ea-8f61-97bcbea7cd91.png)

**Comment by yg** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To claim an issue to work on or need any help, please leave a comment.

**Comment by yg** [comment]
There is an issue already for 404 #570

I can able to reproduce the space bug, I will work on this issue!
