### ISSUE TITLE
Dark mode/theme

### ISSUE THREAD

**Issue by filiptronicek** [open-sauced/open-sauced#607]
### Is your feature request related to a problem? Please describe.
A dark color scheme for the project's web view, loved by a lot of devs. I think this project would really deserve something like this for the open-source night sessions. 

### Describe the solution you'd like
A new dark theme, with a switch to be able to choose from a light (current) or the new dark theme. It could be changed by the [Color Scheme Preference API](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) or with a manual rewrite. A customized [dark-mode-toggle](https://www.npmjs.com/package/dark-mode-toggle) would be an easy to implement solution, that could be customized to the project's needs.

**Comment by yg** [comment]
Thanks for the issue @filiptronicek! We'll take your request into consideration and follow up if we decide to tackle this issue.

To claim an issue to work on or need any help, please leave a comment.

**Comment by yg** [comment]
There is an example implementation using **styled-components** here https://github.com/krofax/Dark-Mode-Using-Styled-Component-In-React-Apps/tree/starter

**Comment by filiptronicek** [comment]
A little idea of how it could look like:
![dark mode](https://user-images.githubusercontent.com/29888641/83955113-d81ec780-a84f-11ea-9b8e-57743c5eeb08.png)

**Comment by filiptronicek** [comment]
Or this: 
![repo view](https://user-images.githubusercontent.com/29888641/83978505-314a3200-a908-11ea-9719-dfc633beebc9.png)

**Comment by filiptronicek** [comment]
Or the original with greater contrast:
![homepage](https://user-images.githubusercontent.com/29888641/83978573-c64d2b00-a908-11ea-903b-c8e359329e66.png)

**Comment by bdougie** [comment]
I think this is a good first pass. I would like to see if we could keep the Hues, but darken them though. 

For example, I took the background color only lowered the Brightness (HSB) to get the following. 

<img width="390" alt="Screenshot 2020-06-07 16 14 53" src="https://user-images.githubusercontent.com/5713670/83982309-b4ed2a00-a8da-11ea-8bab-fa77c7bc76c9.png">

**Comment by Brawrdon** [comment]
So I use [Dark Reader](https://darkreader.org) and didn't even realise that the dark theme officially actually implemented. Here are some screenshots of Dark Reader's attempts at automatically create a dark theme version of the website, they may help in coming up with a colo(u)r scheme!

![Dashboard](https://user-images.githubusercontent.com/9751243/83983294-f5719580-a924-11ea-9464-6c15c3a06369.png)
![Repository](https://user-images.githubusercontent.com/9751243/83983299-01f5ee00-a925-11ea-89be-c881ddfdeb86.png)

**Comment by bdougie** [comment]
Looks like Dark Reader does a good job. It also calls a places where we could improve the UI in regards to color choice for elements.

**Comment by Brawrdon** [comment]
> This looks good. Just needs a lighter font-color

Agreed 😁

**Comment by filiptronicek** [comment]
What do you guys think, which better for a dark mode implementation? Dark grey or black? (I personally implement on every one of my websites a dark mode with a dark grey but just to be all on the same note here)

**Comment by bdougie** [comment]
Dark grey

**Comment by ashawe** [comment]
I would like to take this issue

**Comment by bdougie** [comment]
Please review the [CONTIBUTING.md](https://github.com/open-sauced/open-sauced/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by ashawe** [comment]
.take

**Comment by 0-vortex** [comment]
@filiptronicek I vote dark grey but I think both are valid - people without sight probles or with low contrast monitors will prefer a white vs black contrast while we could use an additional intermediate no-contrast mode, similar to the current GitHub experience :D

**Comment by mtfoley** [comment]
.take

**Comment by mtfoley** [comment]
@bdougie @filiptronicek @0-vortex I've got a draft PR for this.
