### ISSUE TITLE
A lot of space in the infobox

### ISSUE THREAD

**Issue by filiptronicek** [open-sauced/open-sauced#610]
There's just a lot of real estate in the infobox of a repo in the web view.

### Describe the solution you'd like
There could be a lot of info, including - stats, descriptions, tags, language [Thread]?
It would help people with not having to go back and forth from GitHub and Open Sauced.

### Describe alternatives you've considered
It could be also made just smaller, but I think it would be more worth it to "use it all".

### Additional context
**ORIGINAL**:
![ORIGINAL](https://user-images.githubusercontent.com/29888641/83855855-f930cc80-a718-11ea-838a-d703a01b4381.png)
**PROPOSED**: (sorry for the font color, the styling is not to be brought as part of the proposal)
![PROPOSED](https://user-images.githubusercontent.com/29888641/83856518-f84c6a80-a719-11ea-8705-67a6bc3983a0.png)

**Comment by yg** [comment]
Thanks for the issue @filiptronicek :purple_heart:! We'll take your request into consideration and follow up if we decide to tackle this issue.

To claim an issue to work on or need any help, please leave a comment :speech_balloon:

**Comment by yg** [comment]
@filiptronicek We fixed it in #707! WDYT?

![Screenshot](https://user-images.githubusercontent.com/61746440/85856488-b8871900-b7d5-11ea-9f7a-b547b43f2cd0.png)

**Comment by filiptronicek** [comment]
Love it! Awesome addition

**Comment by yg** [comment]
Fixed in #707
