### ISSUE TITLE
Images flicker when page is reload the homepage.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#612]
### Describe the bug

When logging into the app, the screen appears blank. I have discovered this only happens when you log out while on a repo goal page and then log in.

### To Reproduce

1. Navigate to the homepage 
2. Hit refresh

### Expected behavior

Images should not flicker. 

### Screenshots

https://www.loom.com/share/12b0459ec151424f8fab4fd640b9861d
### Desktop

- OS: macOS
- Browser: Chrome
- Version: 86

**Comment by yg** [comment]
Is that because of **serviceworkers**?

**Comment by bdougie** [comment]
I don't think so. I believe the images need a min-height. The image loads at 0 and then expands. 

Images in question

1. User profile image (after login, needs min-width).
2. Pizza Image in the Hero (needs min-height).
3. Quote images (needs min-height).

Bonus: Perhaps we can progressively load the images.

- https://github.com/FormidableLabs/react-progressive-image

```
<ProgressiveImage
  delay={3000}
  src="large-image.jpg"
  placeholder="tiny-image.jpg"
>
  {src => <img src={src} alt="an image" />}
</ProgressiveImage>
```

- https://codeburst.io/how-to-do-simple-progressive-image-loading-in-react-like-medium-dfad4c181b53
- https://github.com/FormidableLabs/react-progressive-image#readme

**Comment by reinitto** [comment]
.take

**Comment by bdougie** [comment]
@reinitto opened a great PR to apply widths to all images, this helps with the page speed load but does not remove the flicker on the images completely. 

> Create smaller quote image versions so they load progressively

I am offering another suggestion, which is to leverage the existing service work on the project. I found that Workbox is built into this app due to it being an of creat-react-app. 

Caching guide: https://web.dev/precache-with-workbox-react/

**Comment by MichaelStevens247** [comment]
Hey guys I am working on this.

**Comment by bdougie** [comment]
Awesome @MichaelStevens247 

Please review the [CONTIBUTING.md](https://github.com/open-sauced/open-sauced/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by MichaelStevens247** [comment]
Tell me if I have this straight:
1. Download code from github
2. Follow instructions from CONTRIBUTING.md in visual studio code terminal
3. Fix the problem.
4. Submit a pull request.

Is this right? This is my first time doing open source.

**Comment by bdougie** [comment]
@MichaelStevens247 that works, be sure to read up on how to assign yourself to issues as well.

**Comment by AshtarCodes** [comment]
.take

**Comment by zordan-tech** [comment]
hi guys I'm first time contributing pls help me

**Comment by jasonericdavis** [comment]
@zordan-tech It looks this issue has already been assigned to @AshtarCodes. The [CONTRIBUTING.md](https://github.com/open-sauced/open-sauced/blob/HEAD/CONTRIBUTING.md) contains information on how to contribute to the project.
