### ISSUE TITLE
Blank notes in repo shows blank scrollbar

### ISSUE THREAD

**Issue by filiptronicek** [open-sauced/open-sauced#618]
### Describe the bug

When you don't have any notes on a repo, it shows an empty horizontal scrollbar
### To Reproduce

1. Go to a repo from the Dashboard
2. Clear the notes

### Expected behavior
A blank div without any scrollbars

### Screenshots

![screenshot of the section](https://user-images.githubusercontent.com/29888641/83890254-d4098180-a74b-11ea-9287-c75145e80b1c.png)

### Desktop

- OS: Windows 10
- Browser: Chrome, Firefox
- Version: Chrome Beta, Firefox Beta

**Comment by filiptronicek** [comment]
It can be resolved by just adding 
```css
.noteContent{
    max-width: 100%;
    overflow-x: hidden;
}
```

**Comment by filiptronicek** [comment]
I'm not sure where the styles for the element are though, @yg can you help?

**Comment by yg** [comment]
@filiptronicek I think if we disable the scrollbar, it will also disabled while there is a note!

@bdougie we need your help!

**Comment by bdougie** [comment]
@filiptronicek here is the spot

/open-sauced/blob/50ea41ffe948c5bc9c9a8f22797b4ad167ef4120/src/styles/TextArea.js#L22-L25

**Comment by filiptronicek** [comment]
@bdougie @yg what max height should the notes be?
