### ISSUE TITLE
UI update for better readability.

### ISSUE THREAD

**Issue by thinkverse** [open-sauced/open-sauced#621]
### Is your feature request related to a problem? Please describe.
Looking around the site I have some issues with the readability of it, the font size is too small and the leading it to close together that even on a big screen it's hard to read, and will lead to poor readability for people with impaired vision.

### Describe the solution you'd like
The recommended minimum for font sizes is `16px`, while not officially stated in the [WCAG Guidelines](https://www.w3.org/WAI/standards-guidelines/wcag/) it is generally agreed upon that `16px` should be the minimum, so I recommend bumping up the minimum sizes for better readability across the site.

### Describe alternatives you've considered
Using the built-in browser zoom works as it should and is a fine alternative but is cumbersome to use.

**Comment by bdougie** [comment]
Thanks so much for opening this up and sharing these guidelines. This is an important consideration and I will make sure we can address this in the next release.

**Comment by bdougie** [comment]
Just did a spin through the repo. We can solve a lot of this by discontinuing usages of the [micro variable](https://github.com/open-sauced/open-sauced/blob/master/src/styles/variables.js#L41) for font-size: https://github.com/open-sauced/open-sauced/search?p=2&q=font-size&unscoped_q=font-size.

Steps to fix: 

1. Remove micro var usage
2. Switch all font-size to use existing variables.

**Comment by Brawrdon** [comment]
> The recommended minimum for font sizes is 16px, while not officially stated in the WCAG Guidelines it is generally agreed upon that 16px should be the minimum, so I recommend bumping up the minimum sizes for better readability across the site.

I think we should be using `rems` to accompany this. We should also think about making the site respect what users set as their expected font size in their browser whether that be higher or lower than 16px, instead of hard coding it. I think most browsers default to 16px anyway.

Here's some possible approaches: https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#Possible_approaches

**Comment by Wachiwi** [comment]
This issue should be closed right? Could you perhaps update what is missing, if something is still left to do? Was looking into it since it was showing here: https://github.com/open-sauced/open-sauced/contribute

**Comment by bdougie** [comment]
All fonts sizes are now variables thanks to #823. All fonts sizes used are not yet aligned with WCAG Guidelines. We still need to update all font sizes below 16px.

**Comment by Wachiwi** [comment]
If it would be ok, I would .take. this and try to look into this one to adapt the font-sizes to the WCAG Guidelines.
