### ISSUE TITLE
Dead repos still show up on dashboard

### ISSUE THREAD

**Issue by Brawrdon** [open-sauced/open-sauced#643]
### Describe the bug
I'm not sure if I should've made this an issue or discussion but... 

I noticed on my dashboard **bdougie/open-sauced** was still taking up a spot after its transfer. 

### To Reproduce

1. Add a repo
2. Wait for that repo to be deleted, renamed or transferred
3. Watch as the old link sits there

### Expected behavior

I'm not sure if it's possible, but it would be cool to see if there's a way to detect if a repository no longer exists and or has been moved. The related issue in the open-sauced-goals repo could then be deleted, updated or a new issue could be made all together.

If it's not possible to detect exactly what's happened to a repo, we could just delete any issue that ends up resolving to a `repo not found` error if they were accessed from click an item on the dashboard.

**Comment by yg** [comment]
Thanks for the issue @Brawrdon :purple_heart:! We'll take your request into consideration and follow up if we decide to tackle this issue.

To claim an issue to work on or need any help, please leave a comment :speech_balloon:

**Comment by yg** [comment]
This is somewhat related to #600

**Comment by bdougie** [comment]
I think we can address this in the goals template. I opened an issue there. Since we are caching the data now, we force updates to issues that are associated to dead repos. 

https://github.com/open-sauced/goals-template/issues/8

**Comment by bdougie** [comment]
This is indeed fixed. We now clear out dead repos with the caching sync 3 times a week.

https://github.com/open-sauced/goals-template/blob/master/.github/workflows/goals-caching.yml
