### ISSUE TITLE
Lint workflow that runs on PR's and Commit 

### ISSUE THREAD

**Issue by NotMoni** [open-sauced/open-sauced#645]
Just Curious. 

cc @yg @bdougie

**Comment by bdougie** [comment]
We don't. There is a lint failure locally but it would be nice to have at the time of the PR, especially for quick changes in the browser. 

I know there are Actions that exist but haven't thought to implement it.

I use https://github.com/marketplace/actions/node-code-formatter in a workshop I teach.

**Comment by NotMoni** [comment]
@bdougie Alright. If you want I can work on a PR for the lint Github actions that runs on commit and PR.

**Comment by bdougie** [comment]
We had to revert the lint.yml addition due to upstream failures. I am reopening this to address again.

**Comment by NotMoni** [comment]
Sounds Good!

**Comment by bdougie** [comment]
@crazy-max brought up the fact that we have no `npm run lint`. It would be good to address that too.

Also mention on the twitch chat today.
https://github.com/kachkaev/video-easter-eggs/blob/e41c32c0c8f5118f2fe17450e5c271b3b0063bcc/.github/workflows/checks.yml#L12-L40

**Comment by JapneetSingh5** [comment]
I think I will be able to add that, would be my first contribution too!

**Comment by bdougie** [comment]
Closing for now as it is not a priority.
