### ISSUE TITLE
Add  lighthouse action to run on PRs.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#647]
### Is your feature request related to a problem? Please describe.

https://github.com/jakejarvis/lighthouse-action

### Describe the solution you'd like

At the moment we have not consider our lighthouse scores. They cover things important metrics for our users. 

### Describe alternatives you've considered

There is the Lighthouse Action that is built in conjunction with the Lighthouse team: https://github.com/marketplace/actions/lighthouse-ci-action.

The difference is the one I am proposing leverages the Netlify Deploy Preview for testing.

### Additional context

I will open a PR to test shortly.

**Comment by yg** [comment]
**FYI!** I use the same CI on my personal website!

Here is an example audit output https://github.com/yg/yg.github.io/runs/716012322?check_suite_focus=true#step:10:250

**Comment by yg** [comment]
Merged!
