### ISSUE TITLE
[UX] Delete and cancel button are easily confused 

### ISSUE THREAD

**Issue by filiptronicek** [open-sauced/open-sauced#650]
### Is your feature request related to a problem? Please describe.
The Delete button near the Notes on a single-repo view changes to a Cancel one when editing a Note. It is really confusing because it kinda looks like a delete button for the notes, not the repo. (I already deleted a few repos accidentally lol)

### Describe the solution you'd like
I have a couple of different ideas:
1. Two buttons
2. Change the text from Delete to Delete repo
3. Add a "Danger zone"

### Additional context
![not editing btn](https://user-images.githubusercontent.com/29888641/84203408-ac971980-aaa9-11ea-8d61-9de23c811e4b.png)
![editing btn](https://user-images.githubusercontent.com/29888641/84203422-b1f46400-aaa9-11ea-9cfa-b6a690d1bc26.png)

**Comment by yg** [comment]
Thanks for the issue @filiptronicek :purple_heart:! We'll take your request into consideration and follow up if we decide to tackle this issue.

To claim an issue to work on or need any help, please leave a comment :speech_balloon:

**Comment by bdougie** [comment]
.take

**Comment by dotundefined** [comment]
I will give this a go. :)

**Comment by filiptronicek** [comment]
@dotundefined would be nice, but probably it would be easier to have just a modal with a "Confirm" button, I find GitHub's technique a bit obnoxious

**Comment by dotundefined** [comment]
@filiptronicek Sure thing! You can go and assign this issue to me. First time contributing btw, I will probably have some more questions. :)

**Comment by filiptronicek** [comment]
Of course, I'm here to help! @dotundefined

**Comment by dotundefined** [comment]
.take

**Comment by dotundefined** [comment]
#829 Is only moving the delete repository button in a separate card. It does not contain confirmation modal, I tought that could be a separate issue.

**Comment by dotundefined** [comment]
@filiptronicek This one is solved. I will create another issue for confirmation modal.
