### ISSUE TITLE
Bug: cancel button doesn't really cancel the note creation

### ISSUE THREAD

**Issue by filiptronicek** [open-sauced/open-sauced#653]
### Describe the bug
When editing notes of a repo, when the cancel button is pressed, the issue isn't updated, but the UI is. A reload solves it, but it should really just revert to it's last state

### To Reproduce
1. Go to a single repo
2. Add notes
3. Hit cancel
4. See the note still appear.

### Expected behavior
The UI is not updated.

### Screenshots
![when editing](https://user-images.githubusercontent.com/29888641/84205864-4fea2d80-aaae-11ea-86ab-ca4cc5cd6864.png)
![cancelled](https://user-images.githubusercontent.com/29888641/84205877-55e00e80-aaae-11ea-93f2-2f258efec02a.png)

### Desktop

- OS: Windows 10
- Browser: Firefox Developer Edition

**Comment by yg** [comment]
Thanks for the issue @filiptronicek :purple_heart:! We'll take your request into consideration and follow up if we decide to tackle this issue.

To claim an issue to work on or need any help, please leave a comment :speech_balloon:

**Comment by bdougie** [comment]
Confirmed this is indeed a bug. 

This can be solved by adding the following to https://github.com/open-sauced/open-sauced/blob/master/src/components/NoteForm.js#L72

```
          <Button primary onClick={_handleToggleEditing && setInput(note)}>
```

This will revert the note to its original state and disregard what was typed.

You could also create a new _handleCancelEditing

```
  const _handleCancelEditing = () => {
    setInput(note)    
    setEditing(false);
  };
```

**Comment by jnielson94** [comment]
.take
