### ISSUE TITLE
Bug: Page loads indefinitely when the repo is misspelled. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#654]
### Describe the bug

When a repo is submitted, there is no validation on the page so a misspelled repo will never load or present an error. 

### To Reproduce

1. Navigate to dashboard.
2. add the repo open-sourced/open-saueced
3. Note the page spins indefinitely.

### Expected behavior

1. Validate that the repo exists on github when submitted.
2. Notify the user does not exist.

### Screenshots

<img width="1259" alt="Screenshot 2020-06-09 15 12 04" src="https://user-images.githubusercontent.com/5713670/84206261-a8480d80-aa63-11ea-9f41-af41d5d18717.png">

### Additional context

This is already an error message displayed when a repo has been renamed. This can be reused or improved while working on this. 

![Screenshot 2020-06-14 07 04 46](https://user-images.githubusercontent.com/5713670/84595560-590c2f00-ae0d-11ea-97ea-13ae3a70c271.png)

https://github.com/open-sauced/open-sauced/blob/e4af8fae1317a30e63364cb0fd93a3735f1d7e3b/src/components/Repository.js#L32-L40

**Comment by bdougie** [comment]
## Solution.

Similar to the [isValidRepoUrl](https://github.com/open-sauced/open-sauced/blob/master/src/lib/util.js) check, there should be a check that returns an error if the is a 404. 

1. Create a function to fetch a status code (404, 200, or 301) from api.github.com.
2. Prevent the creation of a goal if a 404 is returned.  
3. Mock the API and write a test file.

## Status Code function
```js
// repoStatusCode.js

const fetch = require('node-fetch');

export default async repoStatusCode(repoUrl) => {
        const apiRepoUrl = // logic to make normal urls convert normal url to api.github.com/repos/owner/name
	const response = await fetch(apiRepoUrl);
	reuturn response.status;
})();
```

```js
// AddRepoForm.js
    const status = repoStatusCode(urlRef.current.value.replace(/\s+/g, ""));

...
    if (status == 404) {
      urlRef.current.focus();
      console.warn("Repository not found!");
      return;
    }
```

**Comment by yg** [comment]
Aww! @bdougie this is a good idea! :+1:
