### ISSUE TITLE
Feature: Improve the 404 page with more assets. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#655]
### Is your feature request related to a problem? Please describe.

The 404 pages could provide more details. My thought is adding the some recommend issues or projects to this page. 

### Describe the solution you'd like

Instead of an H1, leverage a chat bubble. 

![Screenshot 2020-06-14 06 50 26](https://user-images.githubusercontent.com/5713670/84595235-8fe14580-ae0b-11ea-9e0a-f216960be75d.png)

### Describe alternatives you've considered

Adding Good Frist issues or recommendations would be a nice addition. #344

**Comment by bdougie** [comment]
Final solution

![Untitled_Artwork](https://user-images.githubusercontent.com/5713670/95268067-749bab00-07eb-11eb-8037-1302a4be5fd3.png)

**Comment by dbgithub** [comment]
Hey! Good evening,
**May I contribute to this feature?** I forked the repo and run the site already in local. Looking forward to fit the 404 error page in there.
I need to take a closer look to the project though :smiley:

**Comment by dbgithub** [comment]
> Final solution
> 
> ![Untitled_Artwork](https://user-images.githubusercontent.com/5713670/95268067-749bab00-07eb-11eb-8037-1302a4be5fd3.png)

Uhm.., I'm wondering whether you have a .svg file of this design (@bdougie ), I downloaded as png for the moment to elaborate more on the 404 page.

Cheers

**Comment by bdougie** [comment]
@dbgithub hot off the press. Also sorry I never responded to your message 10 days ago.

https://www.dropbox.com/s/xzxz1ov3r26kiz8/pop%20art%20pizza-01.svg?dl=0

**Comment by dbgithub** [comment]
Hey,
I'm just performed a [pull request for this issue](https://github.com/open-sauced/open-sauced/pull/868). Hoping you'd like it.
Also, I would appreciate if it gets validated for the Hacktoberfest anyways :)

Cheers
