### ISSUE TITLE
Bug: White label is not visible

### ISSUE THREAD

**Issue by yg** [open-sauced/open-sauced#658]
### Describe the bug

White label is not visible

### To Reproduce

1. Create an Issue
1. Create a label with white color
1. Apply the label to the issue

Eg: https://github.com/yg/open-sauced-goals/issues/14

### Expected behavior

Should have the font color automatically based on the label color!

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/61746440/84250780-1eaf4300-ab2a-11ea-882e-029867c7adbe.png)

https://www.loom.com/share/8dfa9235b074446e983efade26370817

**Comment by yg** [comment]
@bdougie, For now, I made something like this! But I need help with figuring the exact condition to change the text color!

```js
color: Number("0x" + label.node.color) > 16000000 ? "#525252" : "white"
```

![Screenshot](https://user-images.githubusercontent.com/61746440/85971266-57845e80-b9ea-11ea-8432-a6603787f78f.png)

**Comment by bdougie** [comment]
What is returned from the API when the label is white? If it is "white", can we just add a condition to replace color with "[offWhite](https://github.com/open-sauced/open-sauced/blob/master/src/styles/variables.js#L6)"?

**Comment by yg** [comment]
@bdougie It returns only the hex value!

https://serve.onegraph.com/short/NX37H8

**Comment by bdougie** [comment]
I think we should add a function to the utils.js the checks for the color white and produce something the [offWhite](https://github.com/open-sauced/open-sauced/blob/master/src/styles/variables.js#L6) color [here](https://github.com/open-sauced/open-sauced/blob/master/src/components/IssueListItem.js#L27).

```
function makeOffWhite(color) {
  if (color === "ffffff" {
     return offWhite
  }
 return color
}
```

Am I missing something?

**Comment by yg** [comment]
> I think we should add a function to the utils.js the checks for the color white and produce something the [offWhite](https://github.com/open-sauced/open-sauced/blob/master/src/styles/variables.js#L6) color [here](https://github.com/open-sauced/open-sauced/blob/master/src/components/IssueListItem.js#L27).
> 
> ```js
> function makeOffWhite(color) {
>   if (color === "ffffff" {
>      return offWhite
>   }
>  return color
> }
> ```
> 
> Am I missing something?

@bdougie This is suitable only for white color! How we are going to handle light colors?

**Comment by bdougie** [comment]
Ah, your function makes sense now. I think rather than check for offwhite or update the background color we should instead check for the lightness of the color and return "light" or "dark." If we setup up a light font color and dark font color we can update the color like so.

```
function fontContrast(color) {
 Number("0x" + label.node.color) > 16000000 ? "dark" : "light"
}
```

Finding the exact point where we should consider the font contrast may take trial and error, but this article looks like a good start. https://awik.io/determine-color-bright-dark-using-javascript/
