### ISSUE TITLE
Feature: Create a Changelog

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#668]
### Is your feature request related to a problem? Please describe.

The need for a changelog is now.

### Describe the solution you'd like

I would like to have the changelog created through automation, but we should start by identifying how to structure the changelog file. 

Do you have any examples of good changelogs?

### Describe alternatives you've considered

I have not managed a changelog and looking for ideas.

**Comment by NotMoni** [comment]
How about a changelog based on commit messsages ?

**Comment by bdougie** [comment]
I think that sounds like a great idea, do you have examples you can link here @NotMoni?

**Comment by NotMoni** [comment]
https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by NotMoni** [comment]
@bdougie  The Conventional Commits specification is a lightweight convention on top of commit messages. It provides an easy set of rules for creating an explicit commit history; which makes it easier to write automated tools on top of. This convention dovetails with SemVer, by describing the features, fixes, and breaking changes made in commit messages.

**Comment by yg** [comment]
@bdougie FYI: https://www.conventionalcommits.org/en/v1.0.0/#:~:text=Summary,automated%20tools%20on%20top%20of.&text=A%20BREAKING%20CHANGE%20can%20be%20part%20of%20commits%20of%20any%20type.

**Comment by bdougie** [comment]
I think next steps here can be.

- [ ] Update CONTRIBUTING.md to recommend all PR titles follow the conventional commits. 
- [ ] Implement [semantic release](https://github.com/semantic-release/semantic-release) or similar automation platform.

**Comment by nthd3gr33** [comment]
I think this will help with this issue:

https://github.com/marketplace/actions/automatic-changelog-generator

**Comment by bdougie** [comment]
This is still ups for grab - https://github.com/open-sauced/open-sauced/issues/668#issuecomment-651759670

**Comment by CodeItQuick** [comment]
Hrmm I see semantic release is mentioned for implementing and updated the contributing, I'll try to plug away at this one over the next few days

**Comment by bdougie** [comment]
Look forward to seeing what you come up with. Feel free to ask questions in the discord.
