### ISSUE TITLE
Feature: Progressive Web App

### ISSUE THREAD

**Issue by yg** [open-sauced/open-sauced#669]
### Is your feature request related to a problem? Please describe.

Implement Progressive Web App for Open Sauced

We can ship :shipit: as both **mobile** and **web** progressive app!

- Mobile Compatible
- Desktop Compatible

**Comment by bdougie** [comment]
I am interested in this. Curious if what changes would need to make this compatible as a PWA? I have not gone this route fully, but have watch PWA space for a while now. 

Are you able to provide a roadmap or checklist of things we can implement today?

**Comment by yg** [comment]
@bdougie Only [`manifest.json`](https://github.com/open-sauced/open-sauced/blob/master/public/manifest.json) file is a place where all works will happen!

Currently, we are also using serviceworkers too, so I think the changes will be smooth.


> Are you able to provide a roadmap or checklist of things we can implement today?

I'll work on this tomorrow (Sunday)

- [ ] Update `manifest.json` file
- [ ] Test in BrowserStack across multiple devices

**Comment by bdougie** [comment]
Perhaps we can update the favicon as well. I can create a new/better one.

**Comment by bdougie** [comment]
![image](https://user-images.githubusercontent.com/5713670/84574866-4850b000-ad5e-11ea-80f1-5855afc68d08.png)

Saw this on dribble today. The are sunsetting their mobile apps and going full PWA.
