### ISSUE TITLE
Bug: Blank page when clicking on profile and coming back (not sure if duplicate)

### ISSUE THREAD

**Issue by akshay5995** [open-sauced/open-sauced#687]
### To Reproduce

1. Go to Home
2. Click on Login
3. (After getting logged in) Click on user profile picture on the top right.'
4. (After getting redirecting to github profile)  Click on the back button

### Expected behavior

Land back where the user left off before getting redirected

### Screenshots

![image](https://user-images.githubusercontent.com/13801224/84685115-e5c90100-af63-11ea-89e2-87e56cbbbc6c.png)

### Desktop

- OS: Windows 10
- Browser: Google chrome
- Version:  83.0.4103.97 (Official Build) (64-bit)

### Smartphone

- Device:
- OS:
- Browser:
- Version:

**Comment by bdougie** [comment]
Related to https://github.com/open-sauced/open-sauced/issues/617 but this issue provides more context.

**Comment by filiptronicek** [comment]
Cannot reproduce on Win10 Firefox, probably cache

**Comment by jnielson94** [comment]
.take
