### ISSUE TITLE
Feature: Configure Access by Organization/Visibility

### ISSUE THREAD

**Issue by jsjoeio** [open-sauced/open-sauced#689]
### Is your feature request related to a problem? Please describe.

The problem is the amount of data (specifically private) the application requests access to.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/3806031/84713573-2acb4400-af20-11ea-9b06-f4ac5c07da89.png">

### Describe the solution you'd like

I would love to be able to limit it to specific organizations or repositories. My GitHub as a lot of sensitive work-related access that I don't want to give access to.

I wish I could configure it so you could only access:
- publicly available information
- non-work-related orgs (i.e. let me pick the orgs)

### Describe alternatives you've considered

Creating a separate GitHub account to try out Open Sauced.

**Comment by bdougie** [comment]
Thanks for bringing this up. I can update the Oauth in the next release, and introduce a GitHub App to allow for fine-grained permissions.  

The quick fix will remove the need for private repos data. 

For those interested, this the path I will be taking. https://developer.github.com/apps/migrating-oauth-apps-to-github-apps/.

**Comment by jsjoeio** [comment]
Cool beans! I'll keep an eye 👀  on this issue then.

**Comment by ZainW** [comment]
login is also pointing to https://serve.onegraph.com/ id that means anything to you, not a big deal but would inspire confidence that im logging into the correct app

**Comment by bdougie** [comment]
> login is also pointing to https://serve.onegraph.com/ id that means anything to you, not a big deal but would inspire confidence that I'm logging into the correct app

That is great feedback, for now, the back is a GitHub repo and the [OneGraph](https://www.onegraph.com/) provides some features that I haven't been able to convince my coworkers to ship :) 

Regarding general confidence, this is definitely used at your own risk. I am hoping to address the major issues by August, maybe sooner depending on contributions. 

If you notice any other security issues, feel to open an issue. I plan to address this one towards the end of the week. As mentioned above, switching to a GitHub App will give me the ability to only ask from the repo generated using this template. 

https://github.com/open-sauced/goals-template

**Comment by bdougie** [comment]
Yo! I walked through the solution sooner than I thought I could. 

I have a [PR](https://github.com/open-sauced/open-sauced/pull/699), that uses a GitHub App. I still need to walk through the following. The Netlify preview on the PR will show you the new permission

1. Adding a screen for to handle transition the existing users to a GitHub that limits the scope.
2. Handle the manual installation to all new/existing users' open-sauced-goals repo.  

I will provide another update when the PR is ready to review.

**Comment by yg** [comment]
Here we go!

![Screenshot](https://user-images.githubusercontent.com/61746440/84857360-81529280-b086-11ea-8a4c-ce294490fcf4.png)

**Comment by bdougie** [comment]
Quick update add to here: https://github.com/open-sauced/open-sauced/pull/699#issuecomment-649126860

**Comment by bdougie** [comment]
@sgrove what are the chances we could have a query in one graph that installs the GitHub App after it is created? I could see this being useful for OneBlog as well. 

My current block for merging the PR, is the process for installation of the Open Sauced GitHub App creates takes the user out of the onboarding experience without the ability to redirect. 

There is an endpoint to install the app via the API, but I am limited because I don't have access to the user token and to make that REST call. This endpoint is not available in the GitHub GraphQL API. 

https://github.com/open-sauced/open-sauced/pull/699#issuecomment-650716746

**Comment by dwwoelfel** [comment]
We've built in an escape hatch for GitHub in case you need to make calls to the REST API that aren't supported by the GraphQL API. It will automatically add the auth we have to the API call. 

[Example query](https://www.onegraph.com/graphiql?shortenedId=PXY8Q5):

```graphql
mutation GitHubRestCall {
  gitHub {
    makeRestCall {
      post(path: "/some-url", jsonBody: {some: "json"}) {
        jsonBody
        response {
          statusCode
        }
      }
    }
  }
}
```

Would that work for you?

**Comment by bdougie** [comment]
> We've built in an escape hatch for GitHub in case you need to make calls to the REST API that aren't supported by the GraphQL API. It will automatically add the auth we have to the API call.

Wow, I always forget about that. Time to final use this.

**Comment by yg** [comment]
> We've built in an escape hatch for GitHub in case you need to make calls to the REST API that aren't supported by the GraphQL API. It will automatically add the auth we have to the API call.

@bdougie We can use this to get `repoStatusCode` too! WDYT?
