### ISSUE TITLE
Remove unused assets and code 

### ISSUE THREAD

**Issue by yg** [open-sauced/open-sauced#691]
**Remove unused assets and code in open-sauced repo**

**Findings**

- [x] **File**: `open-sauced/src/components/sauce-anchor.svg`
- [x] **Folder**: `open-sauced/src/fonts`
- [x] **File**: `open-sauced/src/images/full-sauce.svg`
- [x] **File**: `open-sauced/src/images/one.jpeg` (imported here https://github.com/open-sauced/open-sauced/blob/master/src/images/index.js and not used)
- [x] **File**: `open-sauced/src/images/sauce2.svg`
- [x] **File**: `open-sauced/src/logos/logo2.svg` (imported here https://github.com/open-sauced/open-sauced/blob/master/src/logos/index.js and not used)
- [x] **File**: `open-sauced/src/logos/logo3.svg` (imported here https://github.com/open-sauced/open-sauced/blob/master/src/logos/index.js and not used)
- [x] **File**: `open-sauced/src/logos/logo4.svg` (imported here https://github.com/open-sauced/open-sauced/blob/master/src/logos/index.js and not used)
- [x] **File**: `open-sauced/src/logos/logo5.svg` (imported here https://github.com/open-sauced/open-sauced/blob/master/src/logos/index.js and not used)
- [x] **File**:` open-sauced/src/logos/logo6.svg` (imported here https://github.com/open-sauced/open-sauced/blob/master/src/logos/index.js and not used)
- [x] **File**: `open-sauced/src/logos/logo7.svg` (imported here https://github.com/open-sauced/open-sauced/blob/master/src/logos/index.js and not used)
- [x] **File**: `open-sauced/src/logos/logo8.svg` (imported here https://github.com/open-sauced/open-sauced/blob/master/src/logos/index.js and not used)

**Comment by bdougie** [comment]
I am cool to remove the above list. 👍🏾
