### ISSUE TITLE
Why Github login requires access to private repos?

### ISSUE THREAD

**Issue by ulgens** [open-sauced/open-sauced#696]
This is not a feature request nor bug report, but i think it's something weird and ugly.

I tried to login to the website with Github and it asks me to give permission to access my private repos. Why? Just why? :slightly_smiling_face:

**Comment by bdougie** [comment]
Thanks for the question and the feedback. The goals repo that is created use to be a private repo. 

I will address in https://github.com/open-sauced/open-sauced/issues/689. I have to wait until weekend to and the v0.15.0 release merged because it will break things when I switch over.

**Comment by bdougie** [comment]
closing and providing updates in #689
