### ISSUE TITLE
Feature: Open Sauced name on browser console

### ISSUE THREAD

**Issue by yg** [open-sauced/open-sauced#701]
### Describe the solution you'd like

Just a small fun!

Open Sauced name with pizza on browser console

:wink: 

### Additional context

![Screenshot from 2020-06-17 20-15-40](https://user-images.githubusercontent.com/61746440/84918360-2056a900-b0de-11ea-9816-f00fd4d37479.png)

Inspired from dev.to

![Screenshot from 2020-06-17 20-19-58](https://user-images.githubusercontent.com/61746440/84913261-f7331a00-b0d7-11ea-82e9-c343dc851fa7.png)

**Comment by bdougie** [comment]
I love this idea, we had something at one of my previous jobs. 

![Screenshot 2020-06-17 08 28 54](https://user-images.githubusercontent.com/5713670/84917801-a63e0a00-b074-11ea-8416-641c544832a2.png)

**Comment by bdougie** [comment]
@open-sauced/triage any other suggestions? Or examples?

**Comment by yg** [comment]
![Screenshot from 2020-06-17 20-49-41](https://user-images.githubusercontent.com/61746440/84918360-2056a900-b0de-11ea-9816-f00fd4d37479.png)

**Comment by yg** [comment]
![Screenshot from 2020-06-17 21-45-40](https://user-images.githubusercontent.com/61746440/84922819-0750f680-b0e4-11ea-9da5-542dc6897d22.png)

**Comment by yg** [comment]
![Screenshot from 2020-06-17 21-38-36](https://user-images.githubusercontent.com/61746440/84922846-1041c800-b0e4-11ea-955d-dbddff817b10.png)

**Comment by NotMoni** [comment]
Looks Cool.
