### ISSUE TITLE
Feature/Bug: Don't show issues when not enabled

### ISSUE THREAD

**Issue by filiptronicek** [open-sauced/open-sauced#708]
### Is your feature request related to a problem? Please describe.
When adding repos like [torvalds/linux](https://github.com/torvalds/linux), where there are issues disabled, it will never show any.
https://help.github.com/en/github/managing-your-work-on-github/disabling-issues
![no issues shown](https://user-images.githubusercontent.com/29888641/84993600-cab7e600-b149-11ea-9133-a48b0d3b9822.png)

### Describe the solution you'd like
Perhaps check if the issues are enabled or not first, then it could show the PRs instead.

**Comment by yg** [comment]
Thanks for making this interesting issue @filiptronicek!

**Comment by yg** [comment]
We can use this GraphQL query to check has issues enabled or not

```gql
query { 
  repository(name: "linux", owner: "torvalds") {
    hasIssuesEnabled
  }
}
```
