### ISSUE TITLE
Bug: open-sauced/open-sauced is showing up for all Invalid repository names added

### ISSUE THREAD

**Issue by sujitagarwal** [open-sauced/open-sauced#715]
### Describe the bug
Bug: Open-sauced/Open-sauced is showing up for all Invalid repository name or typo in repository name 

### To Reproduce
Login and go to dashboard
Add a new owner/repo that should be invalid.
Check the added listing

### Expected behavior
Name should be shown or an alert message that invalid repo name/doesn't exist.

### Screenshots

![image](https://user-images.githubusercontent.com/1915009/85042930-6f1d4500-b1a9-11ea-9e6b-4fbd9191a02b.png)

### Desktop

- OS: Win10
- Browser: Mozilla Firefox
- Version: 77.0.1

**Comment by bdougie** [comment]
This was fixed in #728 

![Screenshot 2020-06-26 07 08 29](https://user-images.githubusercontent.com/5713670/85866200-e5a6dd80-b77b-11ea-859f-1c9ebff8f810.png)
