### ISSUE TITLE
Bug: Outdated favicon

### ISSUE THREAD

**Issue by sujitagarwal** [open-sauced/open-sauced#716]
### Expected behavior
Favicon should be updated as per latest logo design

### Screenshots
![image](https://user-images.githubusercontent.com/1915009/85046759-7a26a400-b1ae-11ea-9d0b-2aef4dc7f380.png)

**Comment by yg** [comment]
Thanks for the issue @sujitagarwal :purple_heart:! We'll take your request into consideration and follow up if we decide to tackle this issue.

To claim an issue to work on or need any help, please leave a comment :speech_balloon:

Assets are available in [open-sauced/assets](https://github.com/open-sauced/assets)

**Comment by sujitagarwal** [comment]
dibs

**Comment by bdougie** [comment]
Let me know if you the log rounded or without background. 

Also `.take` works too. https://github.com/open-sauced/open-sauced/blob/master/CONTRIBUTING.md

**Comment by sujitagarwal** [comment]
I think without background might look odd on browsers that run on custom themes. My vote is for a logo with rounded background

**Comment by bdougie** [comment]
![roundedlogo](https://user-images.githubusercontent.com/5713670/85053671-bb3b9b80-b14f-11ea-875b-a7ef9dfca9de.png)

**Comment by sujitagarwal** [comment]
Do you recommend any favicon generator?

**Comment by JapneetSingh5** [comment]
> Do you recommend any favicon generator?

favicon.io is good

**Comment by JapneetSingh5** [comment]
is this issue claimed? 👀👀

**Comment by yg** [comment]
Yes, @JapneetSingh5! It is assigned to @sujitagarwal!
