### ISSUE TITLE
Feature: Add repo icon in context box

### ISSUE THREAD

**Issue by yg** [open-sauced/open-sauced#727]
### Describe the solution you'd like

Add repo icon in context box

### Additional context

![Screenshot](https://user-images.githubusercontent.com/61746440/85217228-0225cd00-b3ac-11ea-8ebf-5b300bb0c6c2.png)

**Comment by JapneetSingh5** [comment]
./take

**Comment by yg** [comment]
@JapneetSingh5 Thanks for jumping in, I assigned to you!

**Comment by JapneetSingh5** [comment]
Hi! I have made a PR #741

**Comment by bdougie** [comment]
Fixed in #719
