### ISSUE TITLE
Feature: Update to Octicon v2

### ISSUE THREAD

**Issue by yg** [open-sauced/open-sauced#744]
### Is your feature request related to a problem? Please describe.

Update to Octicon v2

### Describe the solution you'd like

https://primer.style/octicons-v2

### Additional context

![Screenshot](https://user-images.githubusercontent.com/61746440/85863783-47e5f980-b7e1-11ea-8cfa-7ed88dae5b18.png)

**Comment by bdougie** [comment]
Bumping this to 10.0.0 would be the first start.

https://github.com/open-sauced/open-sauced/blob/master/package.json#L81

**Comment by JapneetSingh5** [comment]
Maybe I can have a go at this?

**Comment by yg** [comment]
Sure @JapneetSingh5 💜!
