### ISSUE TITLE
Feature: Donate button

### ISSUE THREAD

**Issue by filiptronicek** [open-sauced/open-sauced#746]
### Describe the solution you'd like
A button next to the name in the repo view, which will show if FUNDING.yml is properly configured.

![proposal](https://user-images.githubusercontent.com/29888641/85868005-039b2f00-b7ca-11ea-826a-516eb47ad3a8.png)

### Additional context
I don't know if this is possible in the API, to fetch the sponsorship state, but it would be great to show some love.

**Comment by bdougie** [comment]
The limitation with getting this data is that Sponsorship data id not readily available. For example, https://github.com/Vets-Who-Code but has not allowed access data to their org data. This is turned off by default. 

The following returns a 403.
```
query { 
	organization(login: "Vets-Who-Code") {
    sponsorshipsAsMaintainer(first: 1) {
      edges {
        node {
          id
          tier {
            id
          }
        
        }
      }
    }
  }
}
```

I also know that organization sponsorship is still in beta and the API interactions could change. Though this feature would be nice, I don't think it will be valuable to explore at this time.

**Comment by filiptronicek** [comment]
I agree, maybe sometime

**Comment by goatandsheep** [comment]
I think even better than this is to just have a GitHub action for new issues that asks for tips like this https://github.com/goatandsheep/issuehunt-action

**Comment by filiptronicek** [comment]
As interesting of a solution you propose, @goatandsheep. maybe we can just fetch the FUNDING.yml, parse the YAML, and add options for users to donate/sponsor via the links provided. 
Something like (pseudo code)

```
fetch (FUNDING.yml);
for website in FUNDING:
  if website is "github":
    return <Link href="github.com/sponsors/website">
```
