### ISSUE TITLE
Bug: Safari making app screens a bit too large

### ISSUE THREAD

**Issue by filiptronicek** [open-sauced/open-sauced#756]
### Describe the bug
On Safari, a lot of the sections of the app are a bit too big.
### To Reproduce

1. Go to the Dashboard / repo with Safari
1. See the bug

### Expected behavior
The same as in every other browser
### Screenshots
<img width="1428" alt="dashboard view" src="https://user-images.githubusercontent.com/29888641/86166605-5734b200-bb15-11ea-8715-df0ae97af2ec.png">

<img width="1421" alt="repo view" src="https://user-images.githubusercontent.com/29888641/86166874-d2966380-bb15-11ea-9ae2-44c2a9be5c60.png">

### Desktop

- OS: macOS Catalina
- Browser: Safari 
- Version: macOS Catalina

**Comment by yg** [comment]
@filiptronicek Can you please add the Issue title!

**Comment by filiptronicek** [comment]
Of course, sorry for that, didn’t notice.

**Comment by JapneetSingh5** [comment]
.take

**Comment by filiptronicek** [comment]
@JapneetSingh5 could you replicate the issue on your end, or may I offer any help?

**Comment by JapneetSingh5** [comment]
The issue is pretty easy to replicate lol, haven’t really thought of a solution yet. Any insights would be great 👍🏻👍🏻

**Comment by filiptronicek** [comment]
I, unfortunately, don't have access to any access macOS at all most of the time, so I believe I won't be of much help.

**Comment by JapneetSingh5** [comment]
Oh, no problem. I’ll keep you updated 😄

**Comment by JapneetSingh5** [comment]
Apparently safari is showing the site differently when I open a local build and when I open the deployed site.
localhost:
<img width="1680" alt="Screen Shot 2020-07-02 at 11 34 20 PM" src="https://user-images.githubusercontent.com/54809290/86394795-c00a5e80-bcbc-11ea-8d43-b46382cdbbeb.png">
opensauced.pizza:
<img width="1676" alt="Screen Shot 2020-07-02 at 11 34 44 PM" src="https://user-images.githubusercontent.com/54809290/86394826-cbf62080-bcbc-11ea-8a22-8bc11dccf22f.png">

**Comment by JapneetSingh5** [comment]
Does anybody have an idea why this is happening?

**Comment by filiptronicek** [comment]
Looks like a style doesn't load or something, any extensions, or something, that would block it?

**Comment by yg** [comment]
Yes this is happening in BrowserStack too in Safari 13.1

![Screenshot](https://user-images.githubusercontent.com/61746440/86395261-97cf2f80-bcbd-11ea-8980-0ca771a72ffa.png)

**Comment by JapneetSingh5** [comment]
Does any of you have a suggestion? I am clueless about this issue now 😕

**Comment by filiptronicek** [comment]
I agree, this is veeery weird.

**Comment by filiptronicek** [comment]
Ok, I have now access to Browserstack. I have looked into the rendered source with inspect element. I couldn't find any height setting. @yg could you help with this?
Ran on Safari MacOS Catalina
![screenshot of Browserstack Safari](https://user-images.githubusercontent.com/29888641/86495181-8c8d0a00-bd78-11ea-86c7-bde7e46e7716.png)

**Comment by JapneetSingh5** [comment]
The width is messing it up I think. The same 30% width is different sizes in safari vis a vis other browsers.

**Comment by BlueJYT** [comment]
Is this still an issue with the new updates with Safari? I have access to a VM and can go back and go back version by version to see what the issue is.

**Comment by crowtech7** [comment]
Is this issue still open? I'm wanting to contribute to an open-source project (my first time) for Hacktoberfest and looking around. @BlueJYT have you resolved this already?

**Comment by bdougie** [comment]
This issue is still a bug and unassigned. Please review the [CONTIBUTING.md](https://github.com/open-sauced/open-sauced/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by crowtech7** [comment]
Read through the CONTIBUTING.md  **.take** I'm on it. Thank you @bdougie !

**Comment by BlueJYT** [comment]
Sorry about that, wasn't on for a while, unfortunately. Also, I cannot seem to get a command line going for Github (I'm running on a Chromebook 👀) So if you want me to test certain versions of Safari, you might want to @ me.

**Comment by crowtech7** [comment]
@BlueJYT if you're able to narrow down where the issue is specifically that would be great.

**Comment by BlueJYT** [comment]
@crowtech7 I'll get on that whenever I can

**Comment by BlueJYT** [comment]
OK, so here's what it's supposed to be like normally:
![Chrome opensauced](https://user-images.githubusercontent.com/45999974/95634287-897c7680-0a57-11eb-9935-019e4309a7f3.png)

Now here's what it looks like in Safari:
![Screenshot 2020-10-09 at 17 46 22](https://user-images.githubusercontent.com/45999974/95634321-9dc07380-0a57-11eb-92fb-81170096db62.png)
![Screenshot 2020-10-09 at 17 46 13](https://user-images.githubusercontent.com/45999974/95634323-9e590a00-0a57-11eb-800b-6f844928a09b.png)

Same OS and everything. I think the problem is that the resolution is too square, so the elements are clumping abnormally

Here's the configuration:
Safari v13, macOSCatalina, 1280x960 resolution

I also resized Chrome, only to see that the issue isn't there. 
![image](https://user-images.githubusercontent.com/45999974/95634483-04459180-0a58-11eb-8769-7efeb4e26651.png)

This is an issue of how the resolution clumps everything. @filiptronicek, there is a new build of MacOS (Big Sur) that you might want to try.
