### ISSUE TITLE
Feature: Structured note taking for easier private migration.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#773]
### Is your feature request related to a problem? Please describe.

At the moment there is no structure to note-taking. There also now guide for the user on what type of notes would be helpful.

https://github.com/open-sauced/open-sauced/issues/769
https://github.com/open-sauced/open-sauced/issues/772

### Describe the solution you'd like

User can select issues they are interested in and store them in the notes section.
User can identify steps to take onboard and contribute to a project.
User can identify key stakeholders in asking questions. (check for CODEOWNERS file)
User can identify the location the synchronous conversation is happening (probably discord).

My rough thoughts on structured note-taking are based on the way I have taken notes in the past: bdougie/open-sauced-goals#17.

Listing here, so I can eventually open an issue.

### Describe alternatives you've considered

If we could add the remirror social editor, we could use emoji's add prompts to fill out.

 In the [goals template](https://github.com/open-sauced/goals-template), we should add an [issue template](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#creating-issue-templates) some users

### Additional context

Examples on what I am thinking for the template.

Contribution steps:

- [ ] Read the CONTRIBUTING.md
- [ ] Join the socials  Discord / Twitter
- [ ] Choose and assign your issue 
- [ ] Fork and clone the repo

Below could leverage the comments, where each issue update is a comment. Having access to the GitHub app could make this easy.

|issue| status|
|-|-|
|link to issue| notes on progress|
|link to another issue| notes on progress|

**Comment by notBdougie** [comment]
.take
