### ISSUE TITLE
Bug: Exceptional handling service

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#774]
### Is your feature request related to a problem? Please describe.

At the moment we are not tracking errors from usage. Though the user count is low, if may be worth tracking for now. 

### Describe the solution you'd like

https://sentry.io/for/open-source/

or

https://www.bugsnag.com/open-source

### Describe alternatives you've considered

More tests.... :smile:

### Additional context

Does anyone else have options or opinions on this?

**Comment by yg** [comment]
Sentry would be awesome! Their open-source plan is pretty good, I already tried with two of my projects!

PS: We can try showing some useful sentry insights in the admin bar!

**Comment by yg** [comment]
@bdougie I will work on this

List of Errors

![Screenshot](https://user-images.githubusercontent.com/61746440/86554409-261c0d80-bf6b-11ea-9b9c-e215d9e2625e.png)

Error/Exception Page

![Annotation 2020-07-06 092821](https://user-images.githubusercontent.com/61746440/86554415-2a482b00-bf6b-11ea-8c9a-07a5b532c80f.png)

Open Source plan supports up to 5,000,000 events / month

![Screenshot](https://user-images.githubusercontent.com/61746440/86554436-3b913780-bf6b-11ea-96e8-e935ccc6f46e.png)

**Comment by filiptronicek** [comment]
I think Sentry would be great! I never personally used it, but it will make finding erros a lot easier.

**Comment by bdougie** [comment]
Sentry open source application was just submitted.

**Comment by bdougie** [comment]
Sentry has been implemented and working. Currently, no exceptions in production, despite there being a few known bugs.
