### ISSUE TITLE
Bug: App crashes if OneGraph token has expired.

### ISSUE THREAD

**Issue by jasonericdavis** [open-sauced/open-sauced#807]
### Describe the bug

The app will not load if the OneGraph token expires.

### To Reproduce

1. Make sure you are logged into he app.
2. Update the value of the OneGraph token in localStorage to set the expiredDate to a date in the past. 
3. Refresh the page

### Expected behavior

App displays the login screen if the OneGraph token has expired.

### Context

I discovered this because I hadn't logged into the site in safari on my computer for a while and when I went to the page I kept getting the peach background color and that's it.

**Comment by jasonericdavis** [comment]
.take

**Comment by bdougie** [comment]
Interesting, curious if you can record a video via [loom](https://www.loom.com/) to share this.

**Comment by jasonericdavis** [comment]
https://www.loom.com/share/90cba6815c914c5a9715fd66e6153a05

**Comment by bdougie** [comment]
Thanks for sharing the video. We definitely need a redirect when the token expires. 

My first thought is validating the expiration in this service here: https://github.com/open-sauced/open-sauced/blob/main/src/lib/identityActions. But, that is just my first thought though.
