### ISSUE TITLE
Bug: terser-webpack-plugin

### ISSUE THREAD

**Issue by hdJerry** [open-sauced/open-sauced#827]
### Describe the bug
This is just a version issue, there were some breaking changes introduced in 3.0.0 and one of them was "minimum supported Node.js version is 10.13.

### To Reproduce

1. Got to package.json
2. Change the version of terser-webpack-plugin to 2.3.6
3. Go to the terminal in the project directory
4. Do npm install

**Comment by bdougie** [comment]
Curious @hdJerry if there is a reason to support earlier versions of node.

**Comment by hdJerry** [comment]
I guess at the point of my installation I was on node version 8.0. I think I should work for higher versions of node.

**Comment by bdougie** [comment]
If you want to open a PR stating node 10.13 or later is required, it would be appreciated. That way folks don't have to stumble into this themselves. 

Adding it here would be ideal. https://github.com/open-sauced/open-sauced#-prerequisites

**Comment by hdJerry** [comment]
> If you want to open a PR stating node 10.13 or later is required, it would be appreciated. That way folks don't have to stumble into this themselves. Adding it here would be ideal. https://github.com/open-sauced/open-sauced#-prerequisites

I will do that.

**Comment by bdougie** [comment]
@hdJerry can your description and link this to your PR using the [fixes](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) command
