### ISSUE TITLE
Bug: Deleting a repo was presented with a failure due to protected branch permissions

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#833]
### Describe the bug
Deleting a repo was presented with a failure due to protected branch permissions

### To Reproduce

Deleting a repo was presented with a failure due to protected branch permissions

1. Add a repo ...wait for it to show #832 
2. Delete the repo
3. Visit your goals repo to see if it was removed

https://github.com/bdougie/open-sauced-goals/runs/1169979951?check_suite_focus=true#step:6:13

### Expected behavior

There might need to be a local cache or local storage that removes the repo right away. The Action that powers the deletion should work as well.

**Comment by CodeItQuick** [comment]
I really think the dashboard should delete the repo _from the dashboard_ It would be rare for someone to want to delete their repository from github, and if they do want to do such an action it should be done through github, not this dashboard (so you don't get blamed for removing "all their work") kinda thing...
