### ISSUE TITLE
Feature: Delete repository confirmation modal

### ISSUE THREAD

**Issue by dotundefined** [open-sauced/open-sauced#834]
### Is your feature request related to a problem? Please describe.

When deleting a repository, there is no feedback. You just click delete repository button, and repository is gone. It can happen that the user missclicks and there is no way to stop deleting repo.

### Describe the solution you'd like

Create a confirmation modal for deleting repository. Really simple modal that is describing what are you about to do, and confirm and cancel buttons.

Modal should be created with reusability in mind, so that we can reuse this modal for other confirmation cases.

### Describe alternatives you've considered

Another way to achieving this, to use a tooltip/popup on `Delete this repository` click instead of full modal.

### Additional context

Either this: https://primer.style/components/Popover or this https://primer.style/components/Dialog

**Comment by dotundefined** [comment]
@filiptronicek I would proceed with this, once we decide best approach.

**Comment by filiptronicek** [comment]
I think this is a good approach, WDYT @bdougie?

**Comment by bdougie** [comment]
There are current no modals in the app, so I have reservations on add any new libraries to make this work. My preference would be using a simple react component that can be shown or hidden. 

I also this this could be hidden a ... menu similar to how dev.to handles their side bar menu. This is similar to how GitHub handles deletion of repos.

I think I may need to think and on this and provide some mock ups for thoughts. 

The simplest solution would be using the native browser alert() box.

**Comment by dotundefined** [comment]
@bdougie There is already `"@primer/components": "^15.2.2"` dependency, that is why I went with that proposal. But now after looking around in the app, this dependency is not used anywhere. 

But I understand, Modal should follow the same way other styled components are created (Button, Card etc).

I can go forward, and create temp solution with the alert(), or I can also create some mockups then we can discuss further.

**Comment by dotundefined** [comment]
Maybe `Modal` can be based on `Card`. So to have a `ModalCard`, which follows styling of a `Card`, but on top of that adds additional props such as callback(onConfirm), onClose, onOpen etc...

**Comment by bdougie** [comment]
I like that approach and happy with your approach at it.

**Comment by dotundefined** [comment]
Alright, I will .take this issue, and start work on general design of the Modal, then I will post mockups here, then we can review it.

**Comment by Kakashi2998** [comment]
Hi, I am new to open source contributions. Can I start working on it?

**Comment by bdougie** [comment]
It is currently assigned to @dotundefined. Maybe consider working using the app and working on any issues you find while navigating it. Happy to get your feedback. We also have a discord link in the Contributing.md if you have questions.

@dotundefined how are things going on this? Any questions?

**Comment by dotundefined** [comment]
@bdougie I don't have any questions, just swamped with own work so I did not make much progress. Maybe it would be a good idea for @Kakashi2998 to take over, he can maybe implement this much faster.
