### ISSUE TITLE
Feature: Migrate Storybook to latest version(v6.0)

### ISSUE THREAD

**Issue by jasonericdavis** [open-sauced/open-sauced#851]
### Is your feature request related to a problem? Please describe.
This feature request is not related to a problem.

### Describe the solution you'd like
Migrate the Storybook packages to the latest version(v6.0). 

### Describe alternatives you've considered
No alternatives have been considered.

### Additional context
Migrating to the latest version of Storybook will be helpful for contributors making UI changes that need to refer to the Storybook documentation when adding stories.

Storybook has outlined some differences between v5.0 and v6.0, and migration steps  here:
[Storybook 6.0](https://medium.com/storybookjs/storybook-6-0-1e14a2071000)

**Comment by adamxtokyo** [comment]
I can have a look at this tomorrow if it's alright 😃

**Comment by jasonericdavis** [comment]
I created this issue to be approved by the triage team before working on it. If it is accepted you are more than welcome to work on it. So I would first wait for it to be accepted before working on it.

**Comment by bdougie** [comment]
I approve of working on this, with the caveat that a number of the stories are out of date as well. If the person that works on this, could also delete some of the unused stories, that would be appreciated.

**Comment by jasonericdavis** [comment]
@adamxtokyo I can assign this issue to you if you are still interested.

**Comment by adamxtokyo** [comment]
Hey @jasonericdavis,
Yeah do it 👍 Sorry I've been MIA for a bit, but I'll get on it asap 😄

**Comment by jasonericdavis** [comment]
Hello @adamxtokyo are you still working on this issue? 
If so no rush I am just checking-in and if not that is fine and I can remove you as the assignee.

**Comment by adamxtokyo** [comment]
Hey @jasonericdavis, thanks for checking in! And yeah, sorry, I think I took on too much 😓 I personal stuff still waiting for me to take action and this is thus unfortunately low on my priority list atm... I think you better remove me as assignee for now. Apologies I didn't communicate this earlier 🙏

**Comment by jasonericdavis** [comment]
No worries @adamxtokyo I understand. I will remove you as the assignee. Don't hesitate to contribute in the future. 😄
