### ISSUE TITLE
Bug: Replace the current Lighthouse action with the google chrome labs official one.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#858]
### Is your feature request related to a problem? Please describe.

Yeah, currently the Lighthouse checks are broken and not uploading artifacts.

### Describe the solution you'd like

Just copy what Eddie has

https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/blob/develop/.github/workflows/lighthouse-check.yml

See the error message here: https://github.com/open-sauced/open-sauced/actions/runs/324356621

### Describe alternatives you've considered

We could contribute upstream to jakejarvis/lighthouse-action and fix it.

**Comment by 0-vortex** [comment]
I can tackle this one but I can't find Eddie's example. Any specifics or it's a "just works" example ? :D

**Comment by filiptronicek** [comment]
I'm not really confident the Action @bdougie mentioned is an official Google Chrome Labs one, but the one he is referring to is https://github.com/foo-software/lighthouse-check-action, as you can take a look for yourself at https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/6e84ef501c05636ecc7d5f640c7a13a1edbd4628/.github/workflows/lighthouse-check.yml

**Comment by bdougie** [comment]
This is nice to have but closing due to it being stale.
