### ISSUE TITLE
Bug: No validation if a viewed repo is being tracked

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#864]
### Describe the bug

The PR #863 introduces the ability to view any public repo on GitHub. This intoduces a new bug where someone can view a repo, but cannot delete or takes notes on the repo. 

The dashboard should validate if someone has saved the repo to their list.

### To Reproduce

1. Navigate to any repo you have not saved.
2. Click on the edit notes button
3. Save a note.
4. No error is presented and the note is not stored in the goals repo.

### Expected behavior

Instead of showing the notes section. The user should be presented with a "start tracking this repository" button. The endpoint should hit a similar [onRepoCreation](https://github.com/open-sauced/open-sauced/blob/main/src/components/RepositoryGoals.js#L25-L28).

```js
  const onRepoCreation = (id, repo) => {
    dispatch({type: "CREATE", payload: repo});
    setGoalsId(id);
  };

```

The goals list of repos is [stored in the data.json](https://github.com/open-sauced/open-sauced/blob/f239d63dd00770a13982a1bf64a6010f72b05ba7/src/lib/apiGraphQL.js#L296).

https://github.com/open-sauced/goals-template/blob/master/.github/workflows/goals-caching.yml

**Comment by anusha5695** [comment]
Hi @bdougie I can pick this

**Comment by bdougie** [comment]
Please review the [CONTIBUTING.md](https://github.com/open-sauced/open-sauced/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by anusha5695** [comment]
Thank you @bdougie

**Comment by mtfoley** [comment]
This behavior *sort of* changed with PR #980 , in that the router currently doesn't resolve URLs that only include repo owner/name.  There's conceivably an opportunity here to provide a route that doesn't include the goal (issue) number and that would either a) show a page that's more like what's being described here, or b) figure out that the goals cache has said repo listed and redirect to the proper route that includes the goal (issue) number.

For context, here's the relevant portion of `containers/App.js`:
```js
<Switch>
          <Route exact path="/" component={guard(Dashboard)} />
          <Route path="/repos/:repoOwner/:repoName/:id" component={guard(Repository)} />
          <Route path="/callback" component={guard(Dashboard)} />
          <Route exact path="/logout" render={() => (
            isLoggedIn ? (
              handleLogOut()
            ) : (
              <Redirect to="/" />
            )
          )}/>
          <Route component={NoMatch} />
        </Switch>
```
