### ISSUE TITLE
Bug: Goals caching is hardcoded to the master branch

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#865]
### Describe the bug

The way the goals get cached is through the goals-template, which has a default branch as master. If someone changes that to anything else, the caching will fail due to [this](https://github.com/open-sauced/open-sauced/blob/f239d63dd00770a13982a1bf64a6010f72b05ba7/src/lib/apiGraphQL.js#L296). 

### To Reproduce

1. Change the branch name for your open-sauced-goals repo. 
2. Add a new or delete a repo 
3. Navigate to open-sauced-goals logs and not there is an error. 

### Expected behavior

This should point to the HEAD branch instead of directly to master. This will allow flexibility of this branch naming to exist. 

### Additional context

I am not sure HEAD is possible with GraphQL API, but it works REST.

**Comment by PeeyushRawat** [comment]
please assign this to me! also please guide me.

**Comment by bdougie** [comment]
@PeeyushRawat Please review the [CONTIBUTING.md](https://github.com/open-sauced/open-sauced/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by PeeyushRawat** [comment]
.take

**Comment by PeeyushRawat** [comment]
> ### Describe the bug
> The way the goals get cached is through the goals-template, which has a default branch as master. If someone changes that to anything else, the caching will fail due to [this](https://github.com/open-sauced/open-sauced/blob/f239d63dd00770a13982a1bf64a6010f72b05ba7/src/lib/apiGraphQL.js#L296).
> 
> ### To Reproduce
> 1. Change the branch name for your open-sauced-goals repo.
> 2. Add a new or delete a repo
> 3. Navigate to open-sauced-goals logs and not there is an error.
> 
> ### Expected behavior
> This should point to the HEAD branch instead of directly to master. This will allow flexibility of this branch naming to exist.
> 
> ### Additional context
> I am not sure HEAD is possible with GraphQL API, but it works REST.

.take
