### ISSUE TITLE
Feature: Allowing Github codespaces subdomain in Onegraph

### ISSUE THREAD

**Issue by Wachiwi** [open-sauced/open-sauced#867]
### Is your feature request related to a problem? Please describe.

Tried to check out and run the project in Github Codespaces, which works, but I cannot log in since the GitHub codespaces forwarded URL is not allowed.

### Describe the solution you'd like

Perhaps it would be possible to allow the GitHub codespaces subdomain.

### Describe alternatives you've considered

N/A

### Additional context

![image](https://user-images.githubusercontent.com/4199845/97732725-3f773580-1ad7-11eb-9cbf-767179307dfb.png)

**Comment by filiptronicek** [comment]
I agree this would be nice, I would also like to allow gitpod.io, it is a big competitor to Codespaces.

The wildcards will then be:
* *.gitpod.io
* *.apps.codespaces.githubusercontent.com

**Comment by bdougie** [comment]
This is a good idea, I am looking into this and also pinged the onegraph team to make them aware.

**Comment by 0-vortex** [comment]
have some codespaces experience now, can tackle this if it is still an issue

**Comment by bdougie** [comment]
We should look into this now that Codespaces is available for folks.

**Comment by bdougie** [comment]
Actually thinking we should pick this up and also look into creating a docker-compose.yml to make this work on multiple cloud dev environments. 

@0-vortex can you look into that docker-compose.yml party?

**Comment by 0-vortex** [comment]
> Actually thinking we should pick this up and also look into creating a docker-compose.yml to make this work on multiple cloud dev environments.
> 
> @0-vortex can you look into that docker-compose.yml party?

Sure thing, please list all the services you want to investigate so I don't go (too) ham 🔥 🤣

**Comment by 0-vortex** [comment]
@bdougie based on all the investigated services I have an example list of domains that would need "wildcarding":

- `*.githubpreview.dev`, `*.github.dev` from https://0-vortex-open-sauced-5p4wvq37xv6-3000.githubpreview.dev / https://0-vortex-open-sauced-5p4wvq37xv6.github.dev
- `*.gitpod.io` from https://3000-black-gull-yrdjd2ec.ws-eu25.gitpod.io
- `*.repl.co` from https://12c11f31-287f-45db-b652-c9c18596f966.id.repl.co / https://open-sauced.0-vortex.repl.co
- `*.codesandbox.io` from https://4sjox.sse.codesandbox.io
- stackblitz turbo limitations make it unusable
- glitch memory limitations make it unusable

Made the "open in" buttons available in the readme prematurely as none of them can actually log in and perform any actions other than tooling - there are some techniques to SSH tunnel into your own localhost and proxy/run the login URL from localhost, not sure if that effort would make sense; 

Would be really happy to know what the appropriate/optimal approach to this would be, in general, as logging into onegraph and creating an app where one could wildcard all the above is not an option :D

**Comment by bdougie** [comment]
I am not sure wildcard domains can even be added in onegraph. They have a netlify as special a special use case but it would be great to expand that to other cloud ide services. 

FYI @sgrove @dwwoelfel
