### ISSUE TITLE
Bug: Sync to Upstream: All jobs have failed

### ISSUE THREAD

**Issue by nightroman** [open-sauced/open-sauced#912]
### Describe the bug

I've got an email from GitHub actions about "Sync to Upstream: All jobs have failed" in my recently created open-saused repo https://github.com/nightroman/open-sauced-goals

The workflow run is here:
https://github.com/nightroman/open-sauced-goals/actions/runs/598617340

### Expected behavior

I am not sure what this action does and its failure means but it's unlikely designed to fail.
I've tried to rerun it, it fails again.

**Comment by filiptronicek** [comment]
As it seems. it is related to the default branch of the repo. The action tries to fetch main but your default branch is master. This is at least what I've gathered from the logs and the workflow file.

**Comment by nightroman** [comment]
But what is the culprit and how to deal with this issue? Should I rename the branch? I can indeed, it will probably fix my issue but not the issue as such, right?

**Comment by bdougie** [comment]
> As it seems. it is related to the default branch of the repo. The action tries to fetch main but your default branch is master. This is at least what I've gathered from the logs and the workflow file.

This is interesting. Thanks for reporting @nightroman and the triage @filiptronicek. The fix would go here, https://github.com/open-sauced/goals-template/blob/master/.github/workflows/sync-2-upstream.yml#L19

I think it should skip if the user's branch is not main. I also think I might change this action entirely. It is pretty really brittle and contingent on GitHub not updating the Actions API, which they done. 

I think the best solution would be moving this syncing to the Open Sauced GitHub App that gets install on the repo. 

I might have to put some thought into this for the best course of action, but in short, changing your branch to main will work.

**Comment by nightroman** [comment]
I've renamed master to main and rerun jobs -- failure again.

**Comment by nightroman** [comment]
I keep getting these errors. I am going to remove my repository to avoid them. Please let me know you want me to keep it for a while for investigation.

**Comment by bdougie** [comment]
Yeah, I am going to remove the action altogether for now. Need a better approach for this.

**Comment by nightroman** [comment]
I've got an email about the failure. Is this still expected?

**Comment by filiptronicek** [comment]
@nightroman it seems your repo is still on an outdated version of the `open-sauced/goals-template` repo. The easiest thing to do would probably be to delete the repo and initialize it again, or if you're into that somehow pull the commits (this is hard to do since the repo is generated and therefore not a fork).

**Comment by nightroman** [comment]
Thank you. I've removed the repository. Closing.
