### ISSUE TITLE
Bug: Delete this repo sounds scary

### ISSUE THREAD

**Issue by filiptronicek** [open-sauced/open-sauced#932]
### Describe the bug
"Delete this repo" sounds scary to click on, it sounds like you are deleting the repo from GitHub.

### To Reproduce

1. Go to a repo in your dashboard
2. See the button

### Expected behavior
Something like "remove this repo from the dashboard" or "unpin repo" would be better and less scary 👀 

### Screenshots
 
![image](https://user-images.githubusercontent.com/29888641/113450817-e5212e80-9400-11eb-88c6-e5b337cc05bf.png)

### Additional context
Discussed on the GitTrends Twitch stream.

**Comment by cemeiq** [comment]
Hi, @filiptronicek I want to contribute to open-sauced project. Can I take this issue?

**Comment by bdougie** [comment]
@cemeiq see Please review the [CONTIBUTING.md](https://github.com/open-sauced/open-sauced/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

Let us know if you have any questions.

**Comment by cemeiq** [comment]
.take

**Comment by mtfoley** [comment]
For what it's worth @cemeiq, I think one alternate phrase for this button could be something to the effect of "Goal Completed"..

**Comment by 0-vortex** [comment]
We could get rid of "repository" as we are only really able to add "repositories" to open sauced and delete does sound weird. It's really removing the project from the open sauced dashboard - might make sense to say just that ?

**Comment by mtfoley** [comment]
.take
