### ISSUE TITLE
Feature: Update Components to match UI redeisgn

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#936]
### Is your feature request related to a problem? Please describe.

I have connected with a designer to provide some mockups of a slight redesign. Please take note, all the illustrations are placeholders. We can use the existing or these, but I do plan on having an illustrator create all new ones. 

**Landing Page:**
![above-the-fold](https://user-images.githubusercontent.com/5713670/114641889-e411bc00-9ca0-11eb-9651-c69b2cd0d714.png)

_note: there is a new frosted overlay and the nav is updated._ 

**Dashboard:**
![dashboard-no-repos](https://user-images.githubusercontent.com/5713670/114642000-1a4f3b80-9ca1-11eb-8b25-e337322d4aff.jpg)

_note: The are bigger margins left and right. The illustration is placed outside the card, to help with constraint issues._ 

![dashboard-with-repos](https://user-images.githubusercontent.com/5713670/114642169-6c905c80-9ca1-11eb-9bf9-15144401d3e7.jpg)

_note: The list of repos has a top and bottom margin. I prefer it without the margin. This is how it is presently._ 

### Describe the solution you'd like

**New User Flow:**
This is the flow when folks first sign in to open sauced for the first time.

![new-user-dashboard](https://user-images.githubusercontent.com/5713670/114642319-bb3df680-9ca1-11eb-90f0-59510ce2c191.jpg)

_note: margin is tighter in and illustrations flank both sides to tell a story._

![new-user-setup](https://user-images.githubusercontent.com/5713670/114642405-d9a3f200-9ca1-11eb-9825-f3e87b69042c.jpg)

_note: This is currently a screenshot of the GitHub UI. This component will need some new code to interact with GitHub._ 

I would like to see these designs added to the https://design.opensauced.pizza/. This is the design system powered by a storybook. A lot of is out of date and most of it doesn't match event the existing design. 

![repo-dashboard](https://user-images.githubusercontent.com/5713670/114642504-0bb55400-9ca2-11eb-955c-bfa783f4b3a2.jpg)

_note: I dislike more of this design, but sharing for feedback purposes.  I mostly dislike the circles about the icons and the buttons inside of cards._

**User Profile:**

_note: There is no user page today. This will need a new route and components. I would also like to see about how to hook into the API similar to how [Git Trends](https://github.com/brminnick/GitTrends) does_

### Describe what you've considered

My thought is any new components get a `New` identifier appended to it, so it can be merged and iterated without breaking the existing UI. 

Foor example. The Card design includes more shadow and colors. My recommendation is to make a Card2 or CardNew component and add that to the storybook.

### Additional context

I will mostly be iterating on these designs myself moving forward but wanted to share some early concepts and thoughts.

**Comment by bdougie** [comment]
HI folks, sharing this for feedback here. Feel free to use [Discord](https://discord.com/invite/U2peSNf23P) too, all feedback is good feedback.

**Comment by filiptronicek** [comment]
>     * any plans for a dark mode ?

@0-vortex yep, check https://github.com/open-sauced/open-sauced/issues/607

**Comment by RizelBobb** [comment]
.take

**Comment by bdougie** [comment]
Thinking during a discord stream. This should be chopped up into separate issues per screen.

**Comment by blackgirlbytes** [comment]
Just circled back to this. Is there a figma for the designs or am I basing this off of the screenshots attached to this issue? @bdougie ?

**Comment by 0-vortex** [comment]
> Just circled back to this. Is there a figma for the designs or am I basing this off of the screenshots attached to this issue? @bdougie ?

IMHO he better produces a Figma or Sketch so we can use it in our storybooks with the design addon 🔥

**Comment by LuluNwenyi** [comment]
Hi @bdougie 

I’m new to the community and I’d definitely like to give this a go. Is it still open to contributions?

**Comment by mtfoley** [comment]
Hi @LuluNwenyi I get the impression that this one will be a team effort and  @blackgirlbytes is currently assigned so I’m going to assign you also. I would def suggest reading through the [contributing guide](https://docs.opensauced.pizza/contributing/getting-started/). For some background in past streams on https://twitch.tv/bdougieYO @bdougie has indicated that the intent is to refresh the look of the app and that the look in the mock-ups will need some iterating on. Plenty to do!

**Comment by LuluNwenyi** [comment]
Thanks @mtfoley.
Hi @blackgirlbytes, have you started working on this and how can I be of help??

**Comment by bdougie** [comment]
Just a quick update. Apologies ongoing quiet on this. I have been connected to UX designer and they will be taking this over. Appreciate the effort everyone put into the conversation and subject. I will open up well-scoped designed issues in the future.
