### ISSUE TITLE
Feature: replace the Trusted By Icons 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#937]
### Is your feature request related to a problem? Please describe.

<img width="917" alt="Screen Shot 2021-04-20 at 5 14 23 PM" src="https://user-images.githubusercontent.com/5713670/115465006-e8d3f400-a1fb-11eb-89ff-e27ddee5620c.png">

### Describe the solution you'd like

Replace the current ones with the following

https://github.com/dayhaysoos/use-shopping-cart
https://github.com/remirror/remirror
https://github.com/GitTrends/GitTrends
https://github.com/graphql/

**Comment by alotoftype** [comment]
I can take this issue

**Comment by bdougie** [comment]
@alotoftype Please review the [CONTIBUTING.md](https://github.com/open-sauced/open-sauced/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.
