### ISSUE TITLE
Feature: add OneGraph GraphiQL instance locally available

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#950]
### Is your feature request related to a problem? Please describe.

Add [OneGraph GraphiQL](https://www.onegraph.com/graphiql) available locally in the project.

### Describe the solution you'd like

Read about [OneGraph/graphiql-explorer](https://github.com/OneGraph/graphiql-explorer) and implement the [graphiql-explorer-example](https://github.com/OneGraph/graphiql-explorer-example) in open-sauced.

### Additional context

https://clips.twitch.tv/AgreeableCrowdedHedgehogOpieOP-lZn-7CleesaptUf0

**Comment by 0-vortex** [comment]
.take

**Comment by bdougie** [comment]
This would be awesome. Perhaps @sgrove has some pointers on how this be approached.

**Comment by sgrove** [comment]
Depending on how easy you want it to be, you could possibly use https://github.com/OneGraph/graphiql-with-extensions - just a <script> tag on a route!

**Comment by 0-vortex** [comment]
I'm willing to tackle on any level of complexity as long as the end solution "just works" for new contributors :D What do you think ?

**Comment by sgrove** [comment]
Oh, either one should "just work", but it can be nice to have everything self-contained for e.g. styling and whatnot.

You should be able to add in the npm dips for graphiql (not >= 2.0!) and graphiql-explorer, then copy/paste most of https://github.com/OneGraph/graphiql-explorer-example/blob/master/src/App.js to get started quickly.

**Comment by 0-vortex** [comment]
Awesome, thanks a lot, checking it out now !

**Comment by 0-vortex** [comment]
Playing around with [Apollo Studio](https://www.apollographql.com/docs/tutorial/production/) right now, will get back with feedback

**Comment by mtfoley** [comment]
@0-vortex played with a couple of labels here.

**Comment by 0-vortex** [comment]
closing in favour of https://github.com/open-sauced/explore.opensauced.pizza
