### ISSUE TITLE
Bug: check GQL queries for integrity

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#951]
### Describe the bug

Some of the GraphQL queries could have duplicated attributes or otherwise hard to catch issues like `repoQuery`. 

This could be a good first issue for someone interested in learning more about open-sauced and gql as it enables thorough investigation of existing queries.

### To Reproduce

Check out https://github.com/open-sauced/open-sauced/blob/0480f67efe88aff380055734c16cf5321ccf5bd2/src/lib/apiGraphQL.js#L84-L132

### Expected behavior

All queries should be perfect !

### Desktop

- OS: all
- Browser: all
- Version: all

### Smartphone

- Device: all
- OS: all
- Browser: all
- Version: all

### Additional context

https://clips.twitch.tv/TangibleFurtiveHeronGOWSkull-9fopjFOtmCnlRtfm

**Comment by divakar54** [comment]
Hello I am new to open source and would like to start contributing. Can you explain the idea of duplicate attributes?
