### ISSUE TITLE
Feature: improve caching strategy for stars dashboard data

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/open-sauced#954]
### Is your feature request related to a problem? Please describe.

Stars data coming from GitHub is cached.

### Describe the solution you'd like

Have the ability to bypass GQL caching on the dashboard repository list without having to add another repostory to the list.

### Additional context

https://clips.twitch.tv/CuteDepressedPuffinWOOP-giOUmm9N_itsAVEo

**Comment by bdougie** [comment]
This is solved in the https://github.com/open-sauced/open-sauced/pull/1124
