### ISSUE TITLE
Bug: next/prev buttons don’t work for repo issues

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/open-sauced#971]
### To Reproduce

1. Open a goal from the dashboard.
2. Note the issues list for the repo, click “Next”

### Expected behavior
Page would load next group of issues
### Screenshots
![71CE6312-F256-4A12-A63C-7F6B507BC613](https://user-images.githubusercontent.com/3792749/116791589-64019980-aa89-11eb-908b-f9f4713f9d3d.png)

**Comment by mtfoley** [comment]
and of course i can't test the previous button ;-P

**Comment by jasonericdavis** [comment]
This appears to be related to the graphql scope issue. 

### Working:
If you open a repository owned by the open-sauced organization and click the next button (currently only the open-sauced repository has enough issues to enable the next button) the next issues load appropriately. 

### Not Working:
If you open a repository that is not owned by the open-sauced organization and click the next button (example repository: [cassidoo/todometer](https://github.com/cassidoo/todometer) ) the screenshot above appears and the console displays the following message:

`Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'e.data.gitHub.repositoryOwner')`

**Comment by mtfoley** [comment]
Thx for getting this triaged. I’d have to double check but I believe the initial load uses a persisted query while the next/prev use the regular api (which have lesser scope).

**Comment by jasonericdavis** [comment]
It looks like the next/prev are also tied to persisted queries based on the  code from [here](https://github.com/open-sauced/open-sauced/blob/5c7048c4a345c676c4063bcf6b95593dd4c5ed9e/src/components/Issues.js#L38) and  [here](https://github.com/open-sauced/open-sauced/blob/5c7048c4a345c676c4063bcf6b95593dd4c5ed9e/src/lib/apiGraphQL.js#L576)

**Comment by bdougie** [comment]
Yeah,  I think you narrowed this down @jasonericdavis. The cursor needs to be added to the persisted query and the next and previous issue logic needs to be replaced with persisted implementations.  

This persisted queries logic, needs some better documentation and I hope to move it to an npm package for that reason. #96

Also thinking out loud, but I have been considering makings a docs file to help walkthrough these things.

**Comment by mtfoley** [comment]
@bdougie Awesome! Could you also implement next/prev versions of the filtered query for #969 and I could adjust code to make the switch?

**Comment by bdougie** [comment]
@jasonericdavis or @mtfoley if you have a moment today, can you take a look at this PR that solves this. It was thrown together quickly. 

#977

I also opened #976 as a response to some of the things @mtfoley has run into.

**Comment by jasonericdavis** [comment]
@bdougie I can take a look later this afternoon
