### ISSUE TITLE
Feature: Create One Graph Documentation (Include Persisted Queries)

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#976]
### Is your feature request related to a problem? Please describe.

Up until now, I have been the only one interacting with Persisted queries. This is a blocker in shipping to features for contributors. 

### Describe the solution you'd like

- [x] Create docs folder to document the process for contributing
- [ ] Look into automation to update persisted queries (consider security)
- [ ] #1154

### Additional context

Examples of blocked contributions 

#971 
#969

**Comment by 0-vortex** [comment]
does this include docz or should open that as new proposal ?

**Comment by mtfoley** [comment]
Just wanted to capture there was some progress made on this in #1034 (fixing some queries and add some docs) and #1078 / #1086 (docusaurus, https://docs.opensauced.pizza)

**Comment by 0-vortex** [comment]
> Just wanted to capture there was some progress made on this in #1034 (fixing some queries and add some docs) and #1078 / #1086 (docusaurus, https://docs.opensauced.pizza)

I checked the first item in the list last night :D 

<img width="464" alt="Screenshot 2021-07-14 at 13 49 18" src="https://user-images.githubusercontent.com/237133/125617282-be6e6667-34b0-41ca-9712-cae6bde199d9.png">

**Comment by mtfoley** [comment]
Sweet. I think the docs in #1034 had some typos and I'm inclined to make a more detailed thing. I feel like we could do a treatment of:

Query function | persisted vs dynamic and why | affected UI components

**Comment by bdougie** [comment]
Documentation exists. the second bullet is blocked by onegraph and I opened an issue for the 3rd.
