### ISSUE TITLE
Bug: Obscure error when trying to set up CodeTriage for unavailable repo

### ISSUE THREAD

**Issue by diminutivesloop** [open-sauced/open-sauced#979]
### Describe the bug

When trying to set up CodeTriage for a repo that hasn’t been added to CodeTriage an obscure error is presented to the user.

### To Reproduce

1. Add a repo to OpenSauced that hasn’t been added to CodeTriage.
2. In the details page for that repo click “Set up CodeTriage” 
3. A new tab is opened with the error message “Not found. Authentication passthru.” 

### Expected behavior
The user should be prompted to add the repo to CodeTriage.

### Desktop

- OS: Mac OS 
- Browser: Safari
- Version: 14.1

**Comment by bdougie** [comment]
Hey, @diminutivesloop I got to work with https://github.com/finitesingularity/tau, curious if you can share screenshots or the error message. 

![Screen Shot 2021-05-04 at 2 08 58 PM](https://user-images.githubusercontent.com/5713670/117072257-079ab600-ace5-11eb-96bf-dc694a21e911.png)

**Comment by bdougie** [comment]
Oh wait was this because you were not logged into Code Triage?

**Comment by mtfoley** [comment]
I started a PR over on the CodeTriage repo, in hopes to fix this upstream: https://github.com/codetriage/CodeTriage/pull/1645

**Comment by mtfoley** [comment]
> I started a PR over on the CodeTriage repo, in hopes to fix this upstream: [codetriage/CodeTriage#1645](https://github.com/codetriage/CodeTriage/pull/1645)
> 
> I'm marking this as blocked, by [codetriage/CodeTriage#1499](https://github.com/codetriage/CodeTriage/issues/1499)

Closing this now since it was fixed in the CodeTriage repo. Shoutout to @schneems for merging!
