### ISSUE TITLE
Feature: usage guide

### ISSUE THREAD

**Issue by diminutivesloop** [open-sauced/open-sauced#987]
### Is your feature request related to a problem? Please describe.
After creating an account and adding some repos I’m not quite sure how I’m “supposed” to use this tool, or what value it provides over just bookmarking the repos I want to contribute to.

### Describe the solution you'd like
Create a brief usage guide that’s readily accessible from within the ui.

**Comment by bdougie** [comment]
This is a great idea. I created a video to kick start this and hopefully create a guide.opensauced.pizza. If you don't mind I will will use this repo for planning.

**Comment by 0-vortex** [comment]
We could do a "Guide" category in [docs.opensauced.pizza](https://docs.opensauced.pizza/) now 🍕

**Comment by 0-vortex** [comment]
> We could do a "Guide" category in [docs.opensauced.pizza](https://docs.opensauced.pizza/) now 🍕

We are sort of doing this now 😄 🍕
