### ISSUE TITLE
Feature: suggest when adding repos

### ISSUE THREAD

**Issue by diminutivesloop** [open-sauced/open-sauced#988]
### Is your feature request related to a problem? Please describe.

When I want to add a repo I either forget the exact name or don’t remember the owner so I have to look it up first.

### Describe the solution you'd like

When typing in to the owner/repo field possible matches should be suggested. Ideally matching would be against either the owner or repo name in addition to the full owner/repo. This functionality could also facilitate validation so the user wouldn’t have to wait for an error notification to realize they mistyped the repo name.

**Comment by 0-vortex** [comment]
Don't think there is any functionality outside of histograms that the gql can't give us. Having the functionality to search fuzzy search, the complexity seems to be in the user experience and look ahead itself. What are some best practices for fuzzy searching could be a better topic of discussion than a separate system but it feels like it needs some base case first !
BTW, found some boring non-js examples hosted on gh and then https://til.simonwillison.net/github/graphql-search-topics :D

**Comment by mtfoley** [comment]
@0-vortex from the link you sent I was playing with this in https://explore.opensauced.pizza - still needs playing!

```graphql
{
  gitHub {
    search(query: "name:algolia sort:updated-desc", type: REPOSITORY, first: 100) {
      repositoryCount
      nodes {
        ... on GitHubRepository {
          nameWithOwner
          description
          updatedAt
          createdAt
          diskUsage
        }
      }
    }
  }
}
```

**Comment by mtfoley** [comment]
Ok this one is more like it for pasting into https://explore.opensauced.pizza

```graphql
{
  gitHub {
    search(
      query: "\"sauced\" in:name OR \"sauced\" in:owner"
      type: REPOSITORY
      first: 10
    ) {
      repositoryCount
      nodes {
        ... on GitHubRepository {
          nameWithOwner
          forkCount
          stargazerCount
        }
      }
    }
  }
}
```
![image](https://user-images.githubusercontent.com/3792749/128384587-25eaf74d-26ae-4302-bb9b-e15d8a9fe3f3.png)

So we would need to have some kind of debouncing, and I'm already trying to think of how this would get mocked up in Storybook...

**Comment by bdougie** [comment]
Recommendations will be powered using the https://github.com/open-sauced/hot project. For the time being, are looking at stars from other users, but in the future, we can find repos users are contributing to. 

https://api.opensauced.pizza is also a resource that can be leveraged today. Just need to figure out how to present it in the UI.
