### ISSUE TITLE
Feature: Font change FiraCode?

### ISSUE THREAD

**Issue by MarkoShiva** [open-sauced/open-sauced#992]
### Is your feature request related to a problem? Please describe.
On stream Brian suggested to change whole site fonts to single font. 

### Describe the solution you'd like
Change font to the Fira Code. :)

### Describe alternatives you've considered
Change font to the Consolas. :)

### Additional context
This issue is out of context so it can be removed if not needed.

**Comment by filiptronicek** [comment]
I love Fira Code, it looks awesome as a Terminal font, never used it as a web font though...
The thing I like the most about it are ligatures, just look at that `!==`!
![image](https://user-images.githubusercontent.com/29888641/117946814-ebfc6480-b30f-11eb-8802-7080beb523d9.png)

**Comment by bdougie** [comment]
I am loving this. I think there will need to be different weights for the homepage and perhaps the page titles on the dashboard.

![Screen Shot 2021-05-14 at 1 02 16 PM](https://user-images.githubusercontent.com/5713670/118322888-ae850c00-b4b4-11eb-8f0e-409c7ecf10b4.png)

**Comment by 0-vortex** [comment]
Having some issues in development, any chance we can pre-load the fonts with npm and add them to the build process ? Saw there are multiple frameworks leveraging google fonts, wonder if there is a consensus on best practices there.

IMO we could totally use 2 fonts, one for text and one for headings, but I would keep fira out of headings or switch to a condensed version (repo names can be really long) - this is one of those places stories make sense ! :D

**Comment by bdougie** [comment]
I think FiraCode may not be the ideal font family for this. Instead, we may want to looking for a better typeface for the landing page and start there.
